<div class="post clearfix">
    <figure>
        <img src="/dist/tim.php?src=/dist/#images#&w=193&h=193" alt="#title#" />
        <div class="cat-name">
            <span class="base">#categoria#</span>
        </div>
    </figure>
    <div class="content">
        <h2><a href="#url#" title="#title#"">#title#</a></h2>
        <p>#description#</p>
    </div>
    <div class="meta">
        <span class="pull-left">Por <a href="#">#autor#</a> - #dia# #mes# #ano# | <a href="#url#">#post_views# Visualizações</a></span>
        <span class="pull-right"><a href="#url#">Readmore...</a></span>
    </div>
</div>