<figure class="head-section">
    <img src="/dist/tim.php?src=/dist/#images#&w=770&h=433" alt="#title#" />
    <div class="head-section-content">
        <h5>#autor#</h5>
        <h1>#title#</h1>
        <p class="meta">#mes#. #dia#, #ano#&nbsp;&nbsp;|&nbsp;&nbsp;<a href="/cidadeonline/blog-posts/#url_cat#" title="Ver Todos Os Posts De #categoria#">#categoria#</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#comments" title="Total De Comentarios">#post_views# Visualizações</a></p>
    </div>
</figure>