             <div class="row">
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="##">
                        <?php echo $this->translate('{{title}}');?></div>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        #title#
                    </div>
                </div>
                 <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="##">
                        <?php echo $this->translate('{{cnpj}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                        #cnpj#</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="##">
                        <?php echo $this->translate('{{phone}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                        #phone#</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="##">
                        <?php echo $this->translate('{{email}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                        #email#</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="##">
                        <?php echo $this->translate('{{cidade}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                        #cidade#</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="##">
                        <?php echo $this->translate('{{endereco}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                        #endereco#</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="##">
                        <?php echo $this->translate('{{bairro}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                        #bairro#</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="##">
                        <?php echo $this->translate('{{cep}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                        #cep#</div>
                </div>
                 <div class="form-group">
                  <div class="control-label col-md-3 col-sm-3 col-xs-12" for="##">
                         <?php echo $this->translate('{{attachment}}');?>
                    </div>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                            <div class="input-group class-file">
                                <div class="btn btn-primary btn-file">
                                  <i class="ion ion-android-upload"></i>
                                    <span class="file-text">Selecione uma imagem</span>#attachment#
                                </div>
                                <p class="help-block">Max. 32MB</p>
                            </div>
                        </div>
                 </div>
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="##">
                        <?php echo $this->translate('{{description}}');?>
                    </div>
                     <div class="col-md-9 col-sm-9 col-xs-12">
                        #description#</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="##">
                        <?php echo $this->translate('{{access}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                        #access#</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="##">
                        <?php echo $this->translate('{{state}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                        #state#</div>
                </div>
                 #password#
                #id##codigo##empresa##asset_id##security##usr_registration_token##images##role_id##url#
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="##">
                        <?php echo $this->translate('{{created}}');?></div><div class="col-md-8 xdisplay_inputx form-group has-feedback">
                        #created#<span class="fa fa-calendar-o form-control-feedback right"></span></div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="##">
                        <?php echo $this->translate('{{modified}}');?></div><div class="col-md-8 xdisplay_inputx form-group has-feedback">
                        #modified#<span class="fa fa-calendar-o form-control-feedback right"></span></div>
                </div>
            <div class="box-footer">
                <div class="pull-right">
                    #save#<a class="btn btn-danger" href="/users">BTN_VOLTAR_LABEL</a><p>
                </div>
            </div>
             </div>