             <div class="row">
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{password}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
                        #password#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{usr_password_confirm}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
                        #usr_password_confirm#</div>
                </div>
                 #security#
             <div class="box-footer">
                <div class="pull-right">
                    #save#<a class="btn btn-danger" href="<?=$this->url("profile");?>">BTN_VOLTAR_LABEL</a><p>
                </div>
            </div>
             </div>