<div class="x_content">
<div class="col-md-3 col-sm-3 col-xs-12 profile_left">
    <div class="profile_img">
        <!-- end of image cropping -->
        <div id="crop-avatar">
            <!-- Current avatar -->
            <div class="avatar-view" title="Change the avatar">
                <?php
               echo \Base\Model\Check::Image($this->users->images,$this->users->title)?>
            </div>
            <!-- Loading state -->
            <div class="loading" aria-label="Loading" role="img" tabindex="-1"></div>
        </div>
        <!-- end of image cropping -->

    </div>
    <h3><?=$this->users->title?></h3>

    <ul class="list-unstyled user_data">
        <li><i class="fa fa-map-marker user-profile-icon"></i> <?=$this->users->cidade?>, <?=$this->users->bairro?>,<?=$this->users->cep?>
        </li>

        <li>
            <i class="fa fa-phone user-profile-icon"></i> <?=$this->users->phone?>
        </li>

        <li class="m-top-xs">
            <i class="fa fa-envelope user-profile-icon"></i>
            <a href="#"><?=$this->users->email?></a>
        </li>
    </ul>

    <a class="btn btn-warning" href="<?=$this->url('profile')?>"><i class="fa fa-edit m-right-xs"></i>Edit Profile</a>
    <br />

</div>
<div class="col-md-9 col-sm-9 col-xs-12">

    <div class="" role="tabpanel" data-example-id="togglable-tabs">
        <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
            <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">EDITAR MINHA SENHA</a>
            </li>

        </ul>
        <div id="myTabContent" class="tab-content">
            <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">

                <!-- start recent activity -->
                <?php
                echo $this->messages();
                $form = $this->form;
                $form->setAttribute('action',  $this->url('profile',['action'=>"update-password-profile"]));
                $form->setAttribute('class', 'form-geral Manager  form-horizontal form-label-left');
                $this->formElementErrors()
                    ->setMessageOpenFormat('<ul class="nav"><li class="erro-obrigatorio">')
                    ->setMessageSeparatorString('</li>')->render($form);
                echo $this->form()->openTag($form);
                $this->GerarViewHelper()->GerarElement($form);
                $html = $this->partial("update-tpl");
                $primeiro = str_replace(array_keys($this->GerarViewHelper()->getHtml()), array_values($this->GerarViewHelper()->getHtml()), $html);
                echo str_replace(array_keys($this->GerarViewHelper()->getLabels()), array_values($this->GerarViewHelper()->getLabels()), $primeiro);
                echo $this->form()->closeTag();?>
                <!-- end recent activity -->

            </div>


        </div>
    </div>
</div>
</div>