<fildset>
    <legend>FORMULARIO DE MANUTENÇÃO</legend>
    <div class="col-md-8 col-xs-12">
        <div class="x_panel">
            <div class="x_title box-default">
                <h2 class="x_title"><small>GERAL</small></h2>
                <div class="clearfix"></div></div>
            <div class="x_content">

                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{parent_id}}');?></div><div class="col-md-5 col-sm-8 col-xs-12">
                        #parent_id#</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{title}}');?></div><div class="col-md-6 col-sm-9 col-xs-12">
                        #title#</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{url}}');?></div><div class="col-md-5 col-sm-9 col-xs-12">
                        #url#</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3 col-sm-3 col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{description}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                        #description#</div>
                </div>
                #id##codigo##empresa##asset_id##modified##security#</div>
            <div class="box-footer">
                <div class="pull-right">
                    #save##save_copy##btn-voltar#
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-xs-12">
        <div class="x_panel">
            <div class="x_title box-default">
                <h2 class="x_title"><small>IMAGENS</small></h2>
                <div class="clearfix"></div></div>
            <div class="x_content">
                <div class="img-add "><?php echo $this->translate('{{images}}');?>#imagePreview#</div>
                <div class="row">
                    <div class="input-group class-file"><div class="btn btn-primary btn-file"><i class="ion ion-android-upload"></i><span class="file-text">Selecione uma imagem</span><input name="attachment" type="file" id="attachment" />#images#</div><p class="help-block">Max. 32MB</p></div>
                    <div class="clear"></div>
                </div>
            </div>

        </div>

        <div class="x_panel">
            <div class="x_title box-default">
                <h2 class="x_title"><small>DATAS</small></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="form-group">
                    <div class="control-label col-md-4 col-sm-3 col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{state}}');?></div><div class="col-md-8 col-sm-9 col-xs-12">
                        #state#</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-4 col-sm-3 col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{access}}');?></div><div class="col-md-8 col-sm-9 col-xs-12">
                        #access#</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-4 col-sm-4 col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{created}}');?></div><div class="col-md-8 xdisplay_inputx form-group has-feedback">
                        #created#<span class="fa fa-calendar-o form-control-feedback right"></span></div>
                </div>
            </div>

        </div>
    </div>
</fildset>