<div class="row">
<div class="col-md-8 col-xs-12">
<div class="x_panel">
<div class="x_title">
    <h2>Form Basic Elements <small>different form elements</small></h2>
    <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#"><i class="fa fa-wrench"></i></a>
            <ul role="menu" class="dropdown-menu">
                <li><a href="#">Settings 1</a>
                </li>
                <li><a href="#">Settings 2</a>
                </li>
            </ul>
        </li>
        <li><a class="close-link"><i class="fa fa-close"></i></a>
        </li>
    </ul>
    <div class="clearfix"></div>
</div>
<div class="x_content">
<br>
<?php
echo $this->messages();
$form = $this->form;
$form->setAttribute('action', $this->url($this->route, array('controller' => $this->controller, 'action' => $this->action, 'id' => $this->id)));
$form->setAttribute('class', 'form-geral Manager form-horizontal form-label-left');
$this->formElementErrors()
    ->setMessageOpenFormat('<ul class="nav"><li class="erro-obrigatorio">')
    ->setMessageSeparatorString('</li>')->render($form);
echo $this->form()->openTag($form);
$row='<label  for="%s" class="control-label col-md-3 col-sm-3 col-xs-12">%s</label>
    <div class="col-md-9 col-sm-9 col-xs-12">
       %s
       %s
    </div>';

?>

<div class="form-group">
    <?=sprintf($row,strtolower($form->get('title')->getLabel()),
        $form->get('title')->getLabel(),
        $this->formElement($form->get('title')),
        $this->formElementErrors()->render($form->get('title'), ['class' => 'help-block']));
    ?>
</div>
<div class="form-group">
    <?=sprintf($row,strtolower($form->get('email')->getLabel()),
        $form->get('email')->getLabel(),
        $this->formElement($form->get('email')),
        $this->formElementErrors()->render($form->get('email'), ['class' => 'help-block']));
    ?>
</div>
<div class="form-group">
    <?=sprintf($row,strtolower($form->get('phone')->getLabel()),
        $form->get('phone')->getLabel(),
        $this->formElement($form->get('phone')),
        $this->formElementErrors()->render($form->get('phone'), ['class' => 'help-block']));
    ?>
</div>
<div class="form-group">
    <?=sprintf($row,strtolower($form->get('cidade')->getLabel()),
        $form->get('cidade')->getLabel(),
        $this->formElement($form->get('cidade')),
        $this->formElementErrors()->render($form->get('cidade'), ['class' => 'help-block']));
    ?>
</div>
<div class="form-group">
    <?=sprintf($row,strtolower($form->get('cep')->getLabel()),
        $form->get('cep')->getLabel(),
        $this->formElement($form->get('cep')),
        $this->formElementErrors()->render($form->get('cep'), ['class' => 'help-block']));
    ?>
</div>


<div class="form-group">
    <?=sprintf($row,strtolower($form->get('bairro')->getLabel()),
        $form->get('bairro')->getLabel(),
        $this->formElement($form->get('bairro')),
        $this->formElementErrors()->render($form->get('bairro'), ['class' => 'help-block']));
    ?>
</div>

<div class="form-group">
    <?=sprintf($row,strtolower($form->get('endereco')->getLabel()),
        $form->get('endereco')->getLabel(),
        $this->formElement($form->get('endereco')),
        $this->formElementErrors()->render($form->get('endereco'), ['class' => 'help-block']));
    ?>
</div>

<div class="form-group">
    <?=sprintf($row,strtolower($form->get('description')->getLabel()),
        $form->get('description')->getLabel(),
        $this->formElement($form->get('description')),
        $this->formElementErrors()->render($form->get('description'), ['class' => 'help-block']));
    ?>
</div>


<div class="form-group">
    <?=sprintf($row,strtolower($form->get('access')->getLabel()),
        $form->get('access')->getLabel(),
        $this->formElement($form->get('access')),
        $this->formElementErrors()->render($form->get('access'), ['class' => 'help-block']));
    ?>
</div>


<div class="form-group">
    <?=sprintf($row,strtolower($form->get('state')->getLabel()),
        $form->get('state')->getLabel(),
        $this->formElement($form->get('state')),
        $this->formElementErrors()->render($form->get('state'), ['class' => 'help-block']));
    ?>
</div>

<div class="ln_solid"></div>
<div class="form-group">
    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
        <button class="btn btn-primary" type="submit">Cancel</button>
        <button class="btn btn-success" type="submit">Submit</button>
    </div>
</div>
<?php echo $this->form()->closeTag();?>
<div class="clear"></div>
</div>
</div>
</div>
</div>