
           <div id="step-1">
               <fildset>
                   <legend>DADOS DA NOTA</legend>
               <div class="row">
                    <div class="col-md-8 col-sm-12">
                        <div class="form-group">
                            <label class="control-label" for="cliente_id"> <?php echo $this->translate('{{cliente_id}}');?>  </label>
                            #cliente_id#
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2 col-sm-5 col-xs-12">
                        <div class="form-group">
                            <label class="control-label" for="cliente_id"> <?php echo $this->translate('{{tipo}}');?>  </label>
                            <div data-toggle="buttons" class="btn-group radio-tipo">
                            #tipo#
                                </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="form-group">
                            <label class="control-label" for="codigo"> <?php echo $this->translate('{{codigo}}');?>  </label>
                            #codigo#
                        </div>
                    </div>
                    <div class="col-md-2 col-sm-3 col-xs-12">
                        <div class="form-group">
                            <label class="control-label" for="created"> <?php echo $this->translate('{{created}}');?>  </label>
                            #created#
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 col-xs-12">
                        <div class="form-group">
                            <label class="control-label" for="description"> <?php echo $this->translate('{{description}}');?>  </label>
                            #description#
                        </div>
                    </div>
                </div>
                   #id##empresa##asset_id##security##created_by##modified##state#
               </fildset>
            </div>

