<div id="step-3">
    <div class="row">
        <div class="row">
            <div class="col-xs-12  col-md-4 col-sm-6 col-xs-offset-0 col-sm-offset-3 col-md-offset-4" style="text-align: center">
                <div class="form-group">
                    <div data-toggle="buttons" class="btn-group radio-fpgto">
                        #fpgto#
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12  col-md-8 col-xs-offset-0 col-md-offset-2" id="pagamentos" style="text-align: center">
                <h2>SELECIONE A FORMA DE PAGAMENTO</h2>

            </div>
        </div>
    </div>
</div>
