
<div class="col-md-3 col-sm-6 col-xs-12">
    <div class="pricing">
        <div class="title">
            <h2>Tally Box Design</h2>
            <h1>free</h1>
        </div>
        <div class="x_content">
            <div class="">
                <div class="pricing_features">
                    <ul class="list-unstyled text-left">
                        <li><i class="fa fa-times text-danger"></i> 2 years access <strong> to all storage locations</strong></li>
                        <li><i class="fa fa-times text-danger"></i> <strong>Unlimited</strong> storage</li>
                        <li><i class="fa fa-check text-success"></i> Limited <strong> download quota</strong></li>
                        <li><i class="fa fa-check text-success"></i> <strong>Cash on Delivery</strong></li>
                        <li><i class="fa fa-check text-success"></i> All time <strong> updates</strong></li>
                        <li><i class="fa fa-times text-danger"></i> <strong>Unlimited</strong> access to all files</li>
                        <li><i class="fa fa-times text-danger"></i> <strong>Allowed</strong> to be exclusing per sale</li>
                    </ul>
                </div>
            </div>
            <div class="pricing_footer">
                <a role="button" class="btn btn-success" href="javascript:void(0);">Editar <span> now!</span></a>
                <a role="button" class="btn btn-danger" href="javascript:void(0);">Excluir <span> now!</span></a>
            </div>
        </div>
    </div>
</div>

<div class="col-md-3 col-sm-6 col-xs-12">
    <div class="pricing">
        <div class="title">
            <h2>Tally Box Design</h2>
            <h1>free</h1>
        </div>
        <div class="x_content">
            <div class="">
                <div class="pricing_features">
                    <ul class="list-unstyled text-left">
                        <li><i class="fa fa-times text-danger"></i> 2 years access <strong> to all storage locations</strong></li>
                        <li><i class="fa fa-times text-danger"></i> <strong>Unlimited</strong> storage</li>
                        <li><i class="fa fa-check text-success"></i> Limited <strong> download quota</strong></li>
                        <li><i class="fa fa-check text-success"></i> <strong>Cash on Delivery</strong></li>
                        <li><i class="fa fa-check text-success"></i> All time <strong> updates</strong></li>
                        <li><i class="fa fa-times text-danger"></i> <strong>Unlimited</strong> access to all files</li>
                        <li><i class="fa fa-times text-danger"></i> <strong>Allowed</strong> to be exclusing per sale</li>
                    </ul>
                </div>
            </div>
            <div class="pricing_footer">
                <a role="button" class="btn btn-success" href="javascript:void(0);">Editar <span> now!</span></a>
                <a role="button" class="btn btn-danger" href="javascript:void(0);">Excluir <span> now!</span></a>

            </div>
        </div>
    </div>
</div>

<div class="col-md-3 col-sm-6 col-xs-12">
    <div class="pricing">
        <div class="title">
            <h2>Tally Box Design</h2>
            <h1>free</h1>
        </div>
        <div class="x_content">
            <div class="">
                <div class="pricing_features">
                    <ul class="list-unstyled text-left">
                        <li><i class="fa fa-times text-danger"></i> 2 years access <strong> to all storage locations</strong></li>
                        <li><i class="fa fa-times text-danger"></i> <strong>Unlimited</strong> storage</li>
                        <li><i class="fa fa-check text-success"></i> Limited <strong> download quota</strong></li>
                        <li><i class="fa fa-check text-success"></i> <strong>Cash on Delivery</strong></li>
                        <li><i class="fa fa-check text-success"></i> All time <strong> updates</strong></li>
                        <li><i class="fa fa-times text-danger"></i> <strong>Unlimited</strong> access to all files</li>
                        <li><i class="fa fa-times text-danger"></i> <strong>Allowed</strong> to be exclusing per sale</li>
                    </ul>
                </div>
            </div>
            <div class="pricing_footer">
                <a role="button" class="btn btn-success" href="javascript:void(0);">Editar <span> now!</span></a>
                <a role="button" class="btn btn-danger" href="javascript:void(0);">Excluir <span> now!</span></a>

            </div>
        </div>
    </div>
</div>

<div class="col-md-3 col-sm-6 col-xs-12">
    <div class="pricing">
        <div class="title">
            <h2>Tally Box Design</h2>
            <h1>free</h1>
        </div>
        <div class="x_content">
            <div class="">
                <div class="pricing_features">
                    <ul class="list-unstyled text-left">
                        <li><i class="fa fa-times text-danger"></i> 2 years access <strong> to all storage locations</strong></li>
                        <li><i class="fa fa-times text-danger"></i> <strong>Unlimited</strong> storage</li>
                        <li><i class="fa fa-check text-success"></i> Limited <strong> download quota</strong></li>
                        <li><i class="fa fa-check text-success"></i> <strong>Cash on Delivery</strong></li>
                        <li><i class="fa fa-check text-success"></i> All time <strong> updates</strong></li>
                        <li><i class="fa fa-times text-danger"></i> <strong>Unlimited</strong> access to all files</li>
                        <li><i class="fa fa-times text-danger"></i> <strong>Allowed</strong> to be exclusing per sale</li>
                    </ul>
                </div>
            </div>
            <div class="pricing_footer">
                <a role="button" class="btn btn-success" href="javascript:void(0);">Editar <span> now!</span></a>
                <a role="button" class="btn btn-danger" href="javascript:void(0);">Excluir <span> now!</span></a>

            </div>
        </div>
    </div>
</div>