<figure class="head-section">
    <img src="/dist/tim.php?src=/dist/#images#&w=770&h=433" alt="#title#" />
    <div class="head-section-content">
        <h5>#phone# | #email#</h5>
        <h1>#title#</h1>
        <p class="meta">#mes#. #dia#, #ano#&nbsp;&nbsp;|&nbsp;&nbsp;<a href="/cidadeonline/classificadolista/#action#" title="Ver Todos As Opções De #categoria#">#categoria#</a>&nbsp;&nbsp;|&nbsp;&nbsp;
            <a href="#comments" title="Total De Comentarios">#classifcados_views# Visualizações</a></p>
    </div>
</figure>