<div class="span12 post no-margin-left">
    <div class="text">
        <h2><a title="#title#" href="#url#">#title#</a></h2> <!-- Title -->
        <p>#description#</p> <!-- Content -->
        <div class="meta">&nbsp;&nbsp;|&nbsp;&nbsp;#mes#. #dia#, #ano#&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#url#">#classifcados_views# Visualizações</a>
            &nbsp;&nbsp;|&nbsp;&nbsp; 
            <a class="btn btn-small " href="#url_novo#"><span class="icon icon-plus"></span> CADASTRAR ANUNCIO</a>
             &nbsp;&nbsp;|&nbsp;&nbsp; 
            <a class="btn btn-small btn-red btn-remover-classificado" href="#url_remove#"><span class="icon icon-trash"></span> </a>
        </div> <!-- Meta -->
    </div>
</div>