<?php
/**
 * @license © 2005 - 2016 by Zend Technologies Ltd. All rights reserved.
 */


namespace Portal\Model\Posts;

use Base\Model\AbstractModel;
use Base\Model\Check;
use Zend\Db\TableGateway\TableGateway;
use Base\Model\AbstractRepository;
use Zend\Debug\Debug;

/**
 * SIGA-Smart
 *
 * Esta class foi gerada via Zend\Code\Generator.
 */
class PostsRepository extends AbstractRepository
{

    /**
     * __construct Factory Model
     *
     * @param TableGateway $tableGateway
     * @return \Portal\Model\Posts\PostsRepository
     */
    public function __construct(TableGateway $tableGateway)
    {
        // Configurações iniciais do Factory Repository
        $this->tableGateway=$tableGateway;
    }

    public function insert(AbstractModel $model){
        $model->setUrl(Check::Name($model->getTitle()));
        $exist=$this->findBy(['url'=>$model->getUrl()]);
        if($exist->getResult())
        {
            $url=sprintf("%s-%s",$model->getUrl(),date('YmdHis'));
            $model->setUrl($url);
        }

        return parent::insert($model);
    }

    public function update(AbstractModel $set, $where = null)
    {
        if(empty($set->getUrl())){
            $set->setUrl(Check::Name($set->getTitle()));
            $exist=$this->findBy(['url'=>$set->getUrl()]);
            if($exist->getResult())
            {
                $url=sprintf("%s-%s",$set->getUrl(),date('YmdHis'));
                $set->setUrl($url);
            }
        }

        return parent::update($set, $where); // TODO: Change the autogenerated stub
    }

    public function postViews($url)
    {
        $data['post_views'] = 0;
        $exist=$this->findBy(['url'=>$url]);

        if($exist->getResult())
        {
            $post_views=$exist->getData()->current();
            $data['post_views'] =((int)$post_views->getPostViews()+1);
            return $this->tableGateway->update($data, array('id' => $post_views->getId()));
        }

        return false;
    }


}

