<fildset>
<legend>FORMULARIO DE MANUTENÇÃO</legend>
<div class="col-md-8&#x20;col-xs-12">
<div class="x_panel">
<div class="x_title&#x20;box-default">
<h2 class="x_title"><small>GERAL</small></h2>
<div class="clearfix"></div></div>
<div class="x_content">
<div class="form-group">
<div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
<?php echo $this->translate('{{access}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
#access#</div>
</div>
<div class="form-group">
<div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
<?php echo $this->translate('{{description}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
#description#</div>
</div>
<div class="form-group">
<div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
<?php echo $this->translate('{{receber_id}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
#receber_id#</div>
</div>
<div class="form-group">
<div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
<?php echo $this->translate('{{banco_id}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
#banco_id#</div>
</div>
<div class="form-group">
<div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
<?php echo $this->translate('{{url}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
#url#</div>
</div>
<div class="form-group">
<div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
<?php echo $this->translate('{{images}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
#images#</div>
</div>
#id##codigo##empresa##asset_id##state##modified##security#</div>
<div class="box-footer">
<div class="pull-right">
#save#<a class="btn btn-danger" href="/boletos/index/0/1">BTN_VOLTAR_LABEL</a><p>
</div>
</div>
</div>
</div>
<div class="col-md-4&#x20;col-xs-12">
<div class="x_panel">
<div class="x_title&#x20;box-default">
<h2 class="x_title"><small>DATAS</small></h2>
<div class="clearfix"></div></div>
<div class="x_content">
<div class="form-group">
<div class="control-label&#x20;col-md-4&#x20;col-sm-4&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
<?php echo $this->translate('{{created}}');?></div><div class="col-md-8&#x20;xdisplay_inputx&#x20;form-group&#x20;has-feedback">
#created#<span class="fa&#x20;fa-calendar-o&#x20;form-control-feedback&#x20;right"></span></div>
</div></div>

</div>
</div>
</fildset>