<fildset>
    <legend>FORMULARIO DE MANUTENÇÃO</legend>
    <div class="col-md-8 col-xs-12">
        <div class="x_panel">

            <div class="x_content">
                <fieldset>
                    <legend>DADOS GERAIS</legend>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{catid}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                            #catid#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{title}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                            #title#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{email}}');?></div><div class="col-md-6 col-sm-8 col-xs-12">
                            #email#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{phone}}');?></div><div class="col-md-4 col-sm-6 col-xs-12">
                            #phone#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{facebook}}');?></div><div class="col-md-5 col-sm-7 col-xs-12">
                            #facebook#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{site}}');?></div><div class="col-md-5 col-sm-7 col-xs-12">
                            #site#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{url}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                            #url#</div>
                    </div>
                     <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{classifcados_views}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                            #classifcados_views#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{description}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                            #description#</div>
                    </div>
                    #id##codigo##empresa##asset_id##modified##security#
                    #created_by#
            </div>
            <div class="box-footer">
                <div class="pull-right">
                    #save##save_copy##btn-voltar#<p>
                </div>
            </div>
            </fieldset>
        </div>
    </div>
    <div class="col-md-4 col-xs-12">
        <div class="x_panel">
            <fieldset>
                <legend>CADASTRAR IMAGEM</legend>
                <div class="x_content">
                    <div class="img-add "><?php echo $this->translate('{{images}}');?>#imagePreview#</div>
                    <div class="row">
                        <div class="input-group class-file"><div class="btn btn-primary btn-file"><i class="ion ion-android-upload"></i><span class="file-text">Selecione uma imagem</span><input name="attachment" type="file" id="attachment" />#images#</div><p class="help-block">Max. 32MB</p></div>
                        <div class="clear"></div>
                    </div>
                </div>
            </fieldset>

        </div>
    </div>
    <div class="col-md-4 col-xs-12">
        <div class="x_panel">
            <fieldset>
                <legend>DADOS DE CONTROLE</legend>
                <div class="x_content">

                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{access}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                            #access#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{state}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                            #state#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-4 col-sm-4 col-xs-12" for="">
                            <?php echo $this->translate('{{created}}');?></div><div class="col-md-8 xdisplay_inputx form-group has-feedback">
                            #created#<span class="fa fa-calendar-o form-control-feedback right"></span></div>
                    </div>
                </div>
</fildset>
</div>

</div>
</fildset>