<fildset>
<legend>FORMULARIO DE MANUTENÇÃO</legend>
<div class="col-md-8&#x20;col-xs-12">
<div class="x_panel">
<div class="x_content">
    <fildset>
        <legend>DODOS DO USUARIO/CLIENTE</legend>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{empresa}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #empresa#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{title}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #title#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{cnpj}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #cnpj#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{phone}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #phone#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{email}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #email#</div>
    </div>
        </fildset>
    <fildset>
        <legend>ENDEREÇO DO USUARIO/CLIENTE</legend>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{cidade}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #cidade#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{endereco}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #endereco#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{bairro}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #bairro#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{cep}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #cep#</div>
    </div>
        </fildset>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{description}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #description#</div>
    </div>


#id##codigo##asset_id##security##password##usr_registration_token##images#</div>
<div class="box-footer">
<div class="pull-right">
    #save##btn-voltar#
</div>
</div>
</div>
</div>
<div class="col-md-4&#x20;col-xs-12">
<div class="x_panel">
<div class="x_content">
    <fildset>
        <legend>ADCIONAL DO USUARIO/CLIENTE</legend>
    <div class="form-group">
        <div class="control-label&#x20;col-md-4&#x20;col-sm-4&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{access}}');?></div><div class="col-md-8&#x20;col-sm-9&#x20;col-xs-12">
            #access#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-4&#x20;col-sm-4&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{state}}');?></div><div class="col-md-8&#x20;col-sm-8&#x20;col-xs-12">
            #state#</div>
    </div>

    <div class="form-group">
        <div class="control-label&#x20;col-md-4&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{role_id}}');?></div><div class="col-md-8&#x20;col-sm-8&#x20;col-xs-12">
            #role_id#</div>
    </div>

    <div class="form-group">
        <div class="control-label&#x20;col-md-4&#x20;col-sm-4&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{created}}');?></div><div class="col-md-8&#x20;xdisplay_inputx&#x20;form-group&#x20;has-feedback">
            #created#<span class="fa&#x20;fa-calendar-o&#x20;form-control-feedback&#x20;right"></span></div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-4&#x20;col-sm-4&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{modified}}');?></div><div class="col-md-8&#x20;xdisplay_inputx&#x20;form-group&#x20;has-feedback">
            #modified#<span class="fa&#x20;fa-calendar-o&#x20;form-control-feedback&#x20;right"></span></div>
    </div>
        </fildset>
</div>

</div>
</div>
</fildset>