</div> <!-- End Container -->
<div id="bottom">
    <div class="container">
        <div class="row-fluid">

            <div class="span4 widget clearfix">
                <div class="header">
                    <h4>About Us</h4>
                </div>

                <div class="content">
                    <p>Donec dignissim leo sit amet nisl luctus vestibulum. Morbi tortor arcu, aliquet nec aliquet at, convallis ut eros. Sed non tellus mauris, vitae congue ante.</p>
                    <p>Nunc imperdiet malesuada pharetra. Duis sodales, arcu tempus rutrum consectetur, sem ante auctor eros, in vehicula magna mauris sit amet est. Mauris ac eros arcu.</p>
                </div>
            </div> <!-- End Widget -->

            <div class="span4 widget clearfix">
                <div class="tags-cloud">

                    <div class="header">
                        <h4>Tags Cloud</h4>
                    </div>

                    <ul>
                        <?php $cats=$this->HomeHelper()->ExeRead("bs_categorias", " WHERE state=0 AND parent_id<>'' ORDER BY id DESC");
                        if ($cats->getResult()):
                            $tag_categorias ='<li><a href="#url#">#title#</a></li>';
                            foreach ($cats->getData() as $cat) {
                                echo   $this->HomeHelper()->Show($cat, $tag_categorias,"blog-posts");
                            }
                        endif;
                        ?>

                    </ul>

                </div>
            </div> <!-- End Widget -->
            <div class="span4 widget clearfix">
                <div class="">

                    <div class="header">
                        <h4>Mapa Do Site</h4>
                    </div>

                    <ul class="list-arrow-bold">
                    <li><a href="/">HOME</a></li>
                    <?php if(!$this->UserIdentity()->getHasIdentity()):?>
                        <li><a href="<?=$this->url('cidadeonline-pages',['action'=>'cadastro'])?>">CADASTRAR-SE</a></li>
                    <?php else:?>
                        <li><a title="<?=$this->UserIdentity()->getHasIdentity()->title?>" href="<?=$this->url('cidadeonline-pages',['action'=>'minha-conta'])?>">MEUS ANUNCIOS</a> </li>
                    <?php endif;?>
                         <li><a href="<?=$this->url('cidadeonline-pages',['action'=>'politica-de-privacidade'])?>">POLITICA DO SITE</a></li>
                          <li><a href="<?=$this->url('cidadeonline-pages',['action'=>'termos-de-uso'])?>">TERMOS DE USO DO SITE</a></li>
                          <li><a href="<?=$this->url('cidadeonline-pages',['action'=>'sobre-nos'])?>">SOBRE NOS</a></li>
                          <li><a href="<?=$this->url('cidadeonline-pages',['action'=>'perguntas-frequentes'])?>">TIRE SUAS DUVIDAS</a></li>
                
                    </ul>

                </div>
            </div> <!-- End Widget -->

        </div> <!-- End Row-Fluid -->
    </div> <!-- End Container -->
</div> <!-- End Bottom -->

<div id="footer">
    <div class="container">

        <p class="pull-left">Copyright 2016 &nbsp;&nbsp;|&nbsp;&nbsp;Todos Os Direitos Reservados&nbsp;&nbsp;|&nbsp;&nbsp;<a target="_blank" href="//sigasmart.com.br">SIGA-Smart</a></p>
        <ul class="social pull-right">
            <li><a href="#" title="Youtube"><img src="/Portal_city556622/stretched/images/social/f0101/youtube.png" alt="Youtube" /></a></li>
            <li><a href="#" title="LinkedIn"><img src="/Portal_city556622/stretched/images/social/f0101/linkedin.png" alt="LinkedIn" /></a></li>
            <li><a href="#" title="Vimeo"><img src="/Portal_city556622/stretched/images/social/f0101/vimeo.png" alt="Vimeo" /></a></li>
            <li><a href="#" title="Tumblr"><img src="/Portal_city556622/stretched/images/social/f0101/tumblr.png" alt="Tumblr" /></a></li>
            <li><a href="#" title="Flickr"><img src="/Portal_city556622/stretched/images/social/f0101/flickr.png" alt="Flickr" /></a></li>
            <li><a href="#" title="DeviantArt"><img src="/Portal_city556622/stretched/images/social/f0101/deviantart.png" alt="DeviantArt" /></a></li>
            <li><a href="#" title="Delicious"><img src="/Portal_city556622/stretched/images/social/f0101/delicious.png" alt="Delicious" /></a></li>
            <li><a href="#" title="Facebook"><img src="/Portal_city556622/stretched/images/social/f0101/facebook.png" alt="Facebook" /></a></li>
            <li><a href="#" title="Twitter"><img src="/Portal_city556622/stretched/images/social/f0101/twitter.png" alt="Twitter" /></a></li>
        </ul>

    </div> <!-- End Container -->
</div> <!-- End Footer -->

<a href="#" class="scrollup" title="Back to Top!">Scroll</a>

