
<div id="sidebar" class="span4">
    <div class="widget clearfix">
        <?php echo $this->partial('/cidadeonline/portal/tpl/social-indices'); ?>
    </div>
    <!-- End Widget -->

    <div class="widget clearfix">
        <?php echo $this->partial('/cidadeonline/portal/widget/enews-tabs'); ?>
    </div>
    <!-- End Widget -->

    <div class="widget clearfix">
        <?php echo $this->partial('/cidadeonline/portal/widget/sponsors'); ?>
    </div> <!-- End Widget -->

    <div class="widget clearfix">
        <?php echo $this->partial('/cidadeonline/portal/widget/subscribe-form'); ?>
    </div> <!-- End Widget -->


</div> <!-- End Sidebar -->

