<article>
    <header>
        <div class="img">
            <img alt="#title#" title="#title#" src="/dist/tim.php?src=/dist/#images#&w=240&h=120" />
        </div>
        <hgroup>
            <h1>#empresa_title#</h1>
            <h2>#empresa_ramo#</h2>
        </hgroup>
    </header>

    <address>Em: #empresa_cidade#/#empresa_uf#</address>
    <a class="btn" href="/empresa/#url#" title="Ver detalhes de #title#">Ver Detalhes</a>
</article>