<fildset>
<legend>FORMULARIO DE MANUTENÇÃO</legend>
<div class="col-md-8&#x20;col-xs-12">
<div class="x_panel">
<div class="x_title&#x20;box-default">
<h2 class="x_title"><small>GERAL</small></h2>
<div class="clearfix"></div></div>
<div class="x_content">

    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{title}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #title#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{parent_id}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #parent_id#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{is_admin}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #is_admin#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{description}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #description#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{access}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #access#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{state}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #state#</div>
    </div>
    #id##codigo##empresa##asset_id##security#
    </div>

<div class="box-footer">
<div class="pull-right">
    #save##btn-voltar#
</div>
</div>
</div>
</div>
<div class="col-md-4&#x20;col-xs-12">
<div class="x_panel">
<div class="x_title&#x20;box-default">
<h2 class="x_title"><small>DATAS</small></h2>
<div class="clearfix"></div></div>
<div class="x_content">
<div class="form-group">
<div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
<?php echo $this->translate('{{created}}');?></div><div class="col-md-8&#x20;xdisplay_inputx&#x20;form-group&#x20;has-feedback">
#created#<span class="fa&#x20;fa-calendar-o&#x20;form-control-feedback&#x20;right"></span></div>
</div>
<div class="form-group">
<div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
<?php echo $this->translate('{{modified}}');?></div><div class="col-md-8&#x20;xdisplay_inputx&#x20;form-group&#x20;has-feedback">
#modified#<span class="fa&#x20;fa-calendar-o&#x20;form-control-feedback&#x20;right"></span></div>
</div></div>

</div>
</div>
</fildset>