<li class="#child#"> <!-- One -->
    <figure><img src="/dist/tim.php?src=/dist/#images#&w=120&h=120" alt="#autor#" /></figure>
    <div class="content">
        <h5><a href="#">#autor#</a></h5>
        <p class="meta"> #mes# #dia#, #ano# #horas# - <strong><a class="btn-reply" href="#reply-#id#">Responder</a></strong></p>
        <span class="comment-id">1</span>
        <p class="text">#description#</p>
        <div class="reply" id="reply-#id#" style="display: none;">
            #formulario#
            <div class="clearfix"></div>
            <div class="margin-bottom20"></div>
            <div class="data-status"></div>
        </div>
    </div>#resp#
</li>
