<div class="base-rate"> <!-- One -->
    <div class="rate-text">
        <span class="left">CIDADE</span>
        <span class="right">#cidade#</span>
    </div>

</div>
<div class="base-rate"> <!-- One -->
    <div class="rate-text">
        <span class="left">CEP</span>
        <span class="right">#cep#</span>
    </div>

</div>
<div class="base-rate"> <!-- One -->
    <div class="rate-text">
        <span class="left">UF</span>
        <span class="right">#uf#</span>
    </div>

</div>
<div class="base-rate"> <!-- One -->
    <div class="rate-text">
        <span class="left">ENDEREÇO</span>
        <span class="right">#endereco#</span>
    </div>

</div>
<div class="base-rate"> <!-- One -->
    <div class="rate-text">
        <span class="left">PAIS</span>
        <span class="right">#pais#</span>
    </div>
</div>