<div class="post clearfix">
    <figure>
        <img src="/dist/tim.php?src=/dist/#images#&w=193&h=193" alt="#title#" />
        <div class="cat-name">
            <span class="base">#categoria#</span>
        </div>
    </figure>
    <div class="content">
        <h2><a href="#url#" title="#title#"">#title#</a></h2>
        <p>#description#</p>
    </div>
    <div class="meta">
        <span class="pull-left">Fone <a href="#">#phone#</a> - #dia# #mes# #ano# </span>
        <span class="pull-right"><a href="#url#">Ler Mais...</a></span>
    </div>
</div>