<div class="row-fluid">
<div id="main" class="span8 blog-posts image-preloader">

<div class="row-fluid">
    <?php
     //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
    $cat=$this->HomeHelper()->ExeRead("bs_categorias", " WHERE url=?", [$this->id],true);
    $this->HomeHelper()->setSelect(" * ");
    //SE NÃO EXISTIR UM CATEGORIA EU LISTO OS POSTS DE TODAS AS CATEGORIAS
    if (!$cat->getResult()):
        $this->HomeHelper()->setSelect(" a.*,c.title as autor,g.title as categoria ");
        //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
        $posts=$this->HomeHelper()->ExeRead("bs_posts a", " ,bs_users c, bs_categorias g WHERE a.created_by=c.id AND a.catid=g.id  ORDER BY a.created DESC");
        $this->HomeHelper()->setSelect(" * ");
        $html=[];
        if (!$posts->getResult()):
            $this->HomeHelper()->alert($posts->getError());
        else:
            $post_list = $this->partial('/tpl/posts/posts-list');
            $breadcrumb = $this->partial('/tpl/breadcrumb');
            $categorias['categoria']="Categoria";
            $categorias['title']="Geral";

            echo $this->HomeHelper()->Show($categorias, $breadcrumb,"posts");
            ?>
            <div class="sep-border margin-bottom30"></div> <!-- Sep Border -->
            <?php
            foreach ($posts->getData() as $post):
                $html[]=$this->HomeHelper()->Show($post, $post_list,"posts");
            endforeach;
            echo implode(PHP_EOL,$html);
        endif;
     endif;
   //SE EXISTIR UMA CATEGORIA LISTA OS POSTS DA CATEGORIA SELECIONADA
    if ($cat->getResult()):
        $breadcrumb = $this->partial('/tpl/breadcrumb');
        $categorias=$cat->getData();
        $categorias['categoria']="Categoria";
        echo $this->HomeHelper()->Show($categorias, $breadcrumb,"posts");
     ?>
    <div class="sep-border margin-bottom30"></div> <!-- Sep Border -->
    <?php
    $this->HomeHelper()->setSelect(" a.*,c.title as autor,g.title as categoria ");
    //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
    $posts=$this->HomeHelper()->ExeRead("bs_posts a", " ,bs_users c, bs_categorias g WHERE a.created_by=c.id AND a.catid=g.id AND a.catid=?  ORDER BY a.created DESC", [$categorias['id']]);
    $this->HomeHelper()->setSelect(" * ");
    $html=[];
    if (!$posts->getResult()):
        $this->HomeHelper()->alert($posts->getError());
    else:
        $post_list = $this->partial('/tpl/posts/posts-list');
        foreach ($posts->getData() as $post):
            $html[]=$this->HomeHelper()->Show($post, $post_list,"posts");
        endforeach;
        echo implode(PHP_EOL,$html);
    endif;
    endif;
    ?>
    <!-- Four -->

    <nav class="nav-pagination">
        <ul>
            <li class="active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#">6</a></li>
            <li><a href="#">7</a></li>
            <li><a href="#">8</a></li>
            <li><a href="#">9</a></li>
            <li><a href="#">10</a></li>
            <li class="empty-space">....</li>
            <li><a href="#">17</a></li>
        </ul>
        <p>Page 1 of 17</p>
    </nav> <!-- End Nav-Pagination -->

</div> <!-- End Row-Fluid -->

</div> <!-- End Main -->

<div id="sidebar" class="span4">
    <div class="widget clearfix">
        <?php echo $this->partial('/tpl/social-indices'); ?>
    </div>
    <!-- End Widget -->

    <div class="widget clearfix">
        <?php echo $this->partial('/widget/enews-tabs'); ?>
    </div>
    <!-- End Widget -->

    <div class="widget clearfix">
        <?php echo $this->partial('/widget/sponsors'); ?>
    </div> <!-- End Widget -->

    <div class="widget clearfix">
        <?php echo $this->partial('/widget/subscribe-form'); ?>
    </div> <!-- End Widget -->


</div> <!-- End Sidebar -->

</div> <!-- End Row-Fluid -->