<div class="row-fluid">
    <div id="main" class="span8 blog-posts image-preloader">

        <div class="row-fluid">
            <?php
            //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
            $autor=$this->HomeHelper()->ExeRead("bs_users", " WHERE url=?", [$this->id],true);
             //SE EXISTIR UMA CATEGORIA LISTA OS POSTS DA CATEGORIA SELECIONADA
            if (!$autor->getResult()):
                $breadcrumb = $this->partial('/tpl/breadcrumb');
                $categorias['categoria']="Posts";
                $categorias['title']="Autor";
                echo $this->HomeHelper()->Show($categorias, $breadcrumb,"posts");
                $this->HomeHelper()->alert($autor->getError());
            else:
                $breadcrumb = $this->partial('/tpl/breadcrumb');
                $categorias['categoria']="Posts Autor";
                $categorias['title']=$autor->getData()['title'];
                echo $this->HomeHelper()->Show($categorias, $breadcrumb,"posts");
                //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
                $this->HomeHelper()->setSelect(" a.*,g.title as categoria ");
                //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
                $posts=$this->HomeHelper()->ExeRead("bs_posts a", " , bs_categorias g WHERE a.catid=g.id AND a.created_by=?  ORDER BY a.created DESC", [$autor->getData()['id']]);
                $this->HomeHelper()->setSelect(" * ");
                ?>
                <div class="sep-border margin-bottom30"></div> <!-- Sep Border -->
                <?php
                  $html=[];
                if (!$posts->getResult()):
                    $this->HomeHelper()->alert($posts->getError());
                else:
                    $post_list = $this->partial('/tpl/posts/posts-list');
                    foreach ($posts->getData() as $post):
                        $post['autor']=$autor->getData()['title'];
                        $html[]=$this->HomeHelper()->Show($post, $post_list,"posts");
                    endforeach;
                    echo implode(PHP_EOL,$html);
                endif;
            endif;
            ?>
            <!-- Four -->

            <nav class="nav-pagination">
                <ul>
                    <li class="active"><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li><a href="#">6</a></li>
                    <li><a href="#">7</a></li>
                    <li><a href="#">8</a></li>
                    <li><a href="#">9</a></li>
                    <li><a href="#">10</a></li>
                    <li class="empty-space">....</li>
                    <li><a href="#">17</a></li>
                </ul>
                <p>Page 1 of 17</p>
            </nav> <!-- End Nav-Pagination -->

        </div> <!-- End Row-Fluid -->

    </div> <!-- End Main -->

    <div id="sidebar" class="span4">
        <div class="widget clearfix">
            <?php echo $this->partial('/tpl/social-indices'); ?>
        </div>
        <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/enews-tabs'); ?>
        </div>
        <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/sponsors'); ?>
        </div> <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/subscribe-form'); ?>
        </div> <!-- End Widget -->


    </div> <!-- End Sidebar -->

</div> <!-- End Row-Fluid -->