
<div class="row-fluid">
    <div id="main" class="span8 single single-post image-preloader">

        <div class="row-fluid">


<?php

$tpl=$this->partial('/widget/register-form');
echo $this->HomeHelper()->formRegister($tpl);
?>

        </div> <!-- End Row-Fluid -->
    </div> <!-- End Main -->

    <div id="sidebar" class="span4">

        <div class="widget clearfix">
            <?php echo $this->partial('/tpl/social-indices'); ?>
        </div>
        <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/enews-tabs'); ?>
        </div>
        <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/sponsors'); ?>
        </div> <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/subscribe-form'); ?>
        </div> <!-- End Widget -->



    </div> <!-- End Sidebar -->

</div> <!-- End Row-Fluid -->
