<div class="row-fluid">
    <div id="main" class="span8 blog-posts image-preloader">

        <div class="row-fluid">
            <?php
            $categorias['title']="";
            if (empty($this->id)):
                //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
                $empresas=$this->HomeHelper()->ExeRead("bs_classificados", "   ORDER BY id DESC");
                $categorias['title']="Tudo";
               else:
               $categoriaKey=$this->id;
               $empresas=$this->HomeHelper()->ExeRead("bs_classificados", " WHERE catid=?  ORDER BY id DESC",[$this->id]);
               $categorias['title']=$this->HomeHelper()->getCategorias($categoriaKey);
            endif;

            if (!$empresas->getResult()):
                $this->HomeHelper()->alert($empresas->getError());
                else:
                $breadcrumb = $this->partial('/tpl/breadcrumb');
                $categorias['categoria']="Categoria";
                echo $this->HomeHelper()->Show($categorias, $breadcrumb,$this->action);
                ?>
                <div class="sep-border margin-bottom30"></div> <!-- Sep Border -->
                <?php
                $html=[];
                if (!$empresas->getResult()):
                    $this->HomeHelper()->alert($empresas->getError());
                else:
                    $post_list = $this->partial('/tpl/classificados/classificados-list');
                    foreach ($empresas->getData() as $empresa):
                        $empresa['categoria']=$this->HomeHelper()->getCategorias($empresa['catid']);
                        $html[]=$this->HomeHelper()->Show($empresa, $post_list,'classificados');
                    endforeach;
                    echo implode(PHP_EOL,$html);
                endif;
            endif;
            ?>


        </div> <!-- End Row-Fluid -->

    </div> <!-- End Main -->

    <div id="sidebar" class="span4">
        <div class="widget clearfix">
            <?php echo $this->partial('/tpl/social-indices'); ?>
        </div>
        <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/enews-tabs'); ?>
        </div>
        <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/sponsors'); ?>
        </div> <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/subscribe-form'); ?>
        </div> <!-- End Widget -->


    </div> <!-- End Sidebar -->

</div> <!-- End Row-Fluid -->