<div class="row-fluid">
    <div id="main" class="span8 blog-posts image-preloader">

        <div class="row-fluid">
            <?php
            $categorias['title']="";
            if (empty($this->id)):
                //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
                $classificados=$this->HomeHelper()->ExeRead("bs_classificados", "  WHERE (title like ? OR description like ?)  ORDER BY id DESC",["%{$this->filtro['search']}%","%{$this->filtro['search']}%"]);
                $categorias['title']="Tudo";
               else:
                $categoriaKey=$this->id;
                $classificados=$this->HomeHelper()->ExeRead("bs_classificados", " WHERE catid=?  AND (title like ? OR description like ?) ORDER BY id DESC",[$this->id,"%{$this->filtro['search']}%","%{$this->filtro['search']}%"]);
                $categorias['title']=$this->HomeHelper()->getCategorias($categoriaKey);
            endif;
            $breadcrumb = $this->partial('/tpl/breadcrumb');
            $categorias['categoria']="Categoria";
            echo $this->HomeHelper()->Show($categorias, $breadcrumb,$this->action);
            echo $this->partial('/tpl/search',['result'=>$classificados,'url'=>$this->url($this->route,['action'=>$this->action,'id'=>$this->id]),'filtro'=>$this->filtro]);
            if (!$classificados->getResult()):
                $this->HomeHelper()->alert($classificados->getError());
                else: ?>
                <div class="sep-border margin-bottom30"></div> <!-- Sep Border -->
                <?php
                $html=[];
                if (!$classificados->getResult()):
                    $this->HomeHelper()->alert($classificados->getError());
                else:
                    $post_list = $this->partial('/tpl/classificados/classificados-list');
                    foreach ($classificados->getData() as $classificado):
                        $classificado['categoria']=$this->HomeHelper()->getCategorias($classificado['catid']);
                        $html[]=$this->HomeHelper()->Show($classificado, $post_list,'classificados');
                    endforeach;
                    echo implode(PHP_EOL,$html);
                endif;
            endif;
            ?>
            <nav class="nav-pagination">
                <?php
                if ($classificados->getResult()):
                echo $this->paginationControl(
                    $classificados->getData(),
                    'Sliding',
                    '/widget/paginator',
                    ['route' => $this->route,
                        'action'=>$this->action,
                        'id'=>$this->id?$this->id:0]
                );
                echo $this->Html('p')->setText("Pagina")->appendText($this->page)->appendText(" a ")->appendText('10')->appendText(" de ")->appendText($classificados->getResult());
                endif;
                ?>

            </nav> <!-- End Nav-Pagination -->

        </div> <!-- End Row-Fluid -->

    </div> <!-- End Main -->

    <div id="sidebar" class="span4">
        <div class="widget clearfix">
            <?php echo $this->partial('/widget/enews-tabs'); ?>
        </div>
        <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/sponsors'); ?>
        </div> <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/subscribe-form'); ?>
        </div> <!-- End Widget -->


    </div> <!-- End Sidebar -->

</div> <!-- End Row-Fluid -->