
<div class="row-fluid">
    <div id="main" class="span8 single single-post image-preloader">

        <div class="row-fluid">
            <?php
            //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
            $classificados=$this->HomeHelper()->ExeRead("bs_classificados", " WHERE url=?",[$this->id],true);
            if (!$classificados->getResult()):
                $this->HomeHelper()->alert($classificados->getError());
            endif;
            ?>
            <?php
            if ($classificados->getResult()):
                $classificadoSEO=$classificados->getData();
                $this->headMeta()->setProperty('fb:app_id', '162032950871423');

                $this->OpenGraph()->setType('article');

                $this->OpenGraph()->setTitle($classificadoSEO['title']);

                $this->OpenGraph()->setSiteName($this->config->site_name);

                $this->OpenGraph()->setDescription(\Base\Model\Check::Chars($classificadoSEO['description'],100));

                $this->OpenGraph()->setUrl(sprintf("%s/cidadeonline/%s/%s",$this->config->site_url,$this->action,$this->id));
                // $this->OpenGraph()->setLocale('pt', array('pt_BR', 'sr'));
                $this->OpenGraph()->appendImage(sprintf("%s/dist/%s",$this->config->site_url,$classificadoSEO['images']));
                $breadcrumb = $this->partial('/tpl/breadcrumb');
                $emp=$classificados->getData();
                $emp['categoria']=$this->HomeHelper()->getCategorias($emp['catid']);
                $emp['url']=$emp['catid'];
                echo $this->HomeHelper()->Show($emp, $breadcrumb,'classificadolista');

            endif;
            ?>
            <?php
            if ($classificados->getResult()):
                $emp_figure = $this->partial('/tpl/classificados/classificados-figure');
                $emp=$classificados->getData();
                $emp['categoria']=$this->HomeHelper()->getCategorias($emp['catid']);
                $emp['url_cat']=$emp['catid'];
                $emp['action']=$emp['catid'];
                echo $this->HomeHelper()->Show($emp, $emp_figure,"classificadolista");
            endif;
            ?>
            <div class="content">
                <?php
                if ($classificados->getResult()):
                    $this->HomeHelper()->tirar=false;
                    echo $this->HomeHelper()->Show($classificados->getData(), "#description#",$emp['catid']);
                    $this->HomeHelper()->tirar=true;
                endif;
                ?>

                </p>


            </div> <!-- End Content -->

            <div class="sep-border no-margin-bottom"></div> <!-- Separator -->

            <div class="prevnext-posts clearfix">
                <?php

                if ($classificados->getResult()):
                    $postId=$classificados->getData();
                    $navigation=$this->HomeHelper()->ExeRead("bs_classificados", " WHERE id<? LIMIT 1", [$postId['id']],true);
                    if($navigation->getResult()){
                        $navprev=$navigation->getData();
                        $navprev['desc']=$navprev['title'];
                        echo $this->HomeHelper()->Show($navprev, $this->partial('/tpl/prev',['prev'=>"Proximo"]),"empresa",5,38);
                    }
                endif;
                if ($classificados->getResult()):
                    $postId=$classificados->getData();
                    $navigation=$this->HomeHelper()->ExeRead("bs_classificados", " WHERE id>? LIMIT 1", [$postId['id']],true);
                    if($navigation->getResult()){
                        $navnext=$navigation->getData();
                        $navnext['desc']=$navnext['title'];
                        echo $this->HomeHelper()->Show($navnext, $this->partial('/tpl/next',['next'=>"Anterior"]),"classificados",5,38);
                    }
                endif;
                ?>
            </div> <!-- End PrevNext-Posts -->

            <div class="sep-border no-margin-top"></div> <!-- Separator -->

            <div class="related-posts">
                <h3>Classificados Relacionadas</h3>
                <?php
                if ($classificados->getResult()):
                    $classificadoId=$classificados->getData();
                    //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
                    $empresasRelacionadas=$this->HomeHelper()->ExeRead("bs_classificados", " WHERE catid=? AND id<>? ORDER BY created DESC LIMIT 4", [$classificadoId['catid'],$classificadoId['id']]);
                    $html=[];
                    if (!$empresasRelacionadas->getResult()):
                        $this->HomeHelper()->alert($empresasRelacionadas->getError());
                    else:
                        $nomargin=" no-margin-left";
                        foreach ($empresasRelacionadas->getData() as $classificado):
                            $post['nomargin']=$nomargin;
                            $html[]=$this->HomeHelper()->Show($classificado, $this->partial('/widget/related-post'),"classificados",5);
                            $nomargin="";

                        endforeach;

                        echo implode(PHP_EOL,$html);
                    endif;
                endif;
                ?>

            </div> <!-- End Related-Posts -->

            <div class="sep-border"></div> <!-- Separator -->
            <div id="comments">
                <div id="load-comments">

                </div>
                <?php
                if($this->user):
                    if ($classificados->getResult()):
                        $classificadoId=$classificados->getData();
                        $data['title']=$classificadoId['title'];
                        $data['html']=$this->partial('/widget/comments-form');
                        $data['parent_id']=$classificadoId['id'];
                        $data['parent']='classificado';
                        $data['tipo']='0';
                        $data['id_form']="Comentarios";
                        echo  $this->HomeHelper()->formComentarios($data);
                    endif;
                else:?>
                    <div class="alert alert-warning">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <strong>OPPSS!</strong> Somente Usuarios Logados Podem Comentar
                    </div>
                <?php endif; ?>
            </div> <!-- End Comments -->


        </div> <!-- End Row-Fluid -->
    </div> <!-- End Main -->

    <div id="sidebar" class="span4">

        <div class="widget clearfix">
            <?php
            $classificadoSEO['url_share']=sprintf("%s/cidadeonline/%s/%s",$this->config->site_url,$this->action,$this->id);
            echo $this->partial('/tpl/social-indices',['postSEO'=>$classificadoSEO]); ?>
        </div>
        <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/enews-tabs'); ?>
        </div>
        <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/sponsors'); ?>
        </div> <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/subscribe-form'); ?>
        </div> <!-- End Widget -->



    </div> <!-- End Sidebar -->

</div> <!-- End Row-Fluid -->
<?php
if ($classificados->getResult()):
    $postId=$classificados->getData();
    ?>
    <script type="text/javascript" src="/Portal_city556622/stretched/js/comments.js"></script>
    <script>
        $(function(){
            var conteudo=$('#load-comments');
            conteudo.load('<?=$this->url('cidadeonline-pages', array('controller' => 'cidadeonline', 'action' => 'loadcommentsclassificados','id'=>$postId['id']))?>');
        })
    </script>
<?php endif;?>
