<?php
$cache=$this->CacheHelper();
$issusers=$cache->getItem('issusers');
$dadosCidade=$this->HomeHelper()->getDadosCidade($issusers['municipio']);
$issusers['city']=$dadosCidade['title'];
?>
<div class="row-fluid">
   <div id="main" class="span8 page contact-page image-preloader">
  
    <div class="row-fluid">
    
     <h1><?=$issusers['title']?></h1>
     <p> <?=\Base\Model\Check::Words($issusers['description'],30);?></p>
        <?php
           echo  $this->HomeHelper()->formContato($this->partial('/widget/contato-form'));
       ?>
   
    </div> <!-- End Row-Fluid -->
   </div> <!-- End Main -->
  
   <div id="sidebar" class="span4">

    <div class="widget clearfix">
     <div class="contact-details">
     
      <div class="header">
       <h4>Contact Informations</h4>
      </div>
      
      <div class="content">
       <p><strong><?=$issusers['title']?></strong></p>
       <p><?=$issusers['numero']?> <?=$issusers['logradouro']?> <?=$issusers['city']?></p>
       <p><?=$dadosCidade['xpais']?>, <?=$issusers['uf']?>, <?=$issusers['cep']?></p>
       <p>Call: <i>+<?=$issusers['phone']?></i></p>
       <p>Email: <a href="#"><?=$issusers['email']?></a></p>
      </div>
     
     </div>
    </div> <!-- End Widget -->
    
    <div class="widget clearfix">
     <div class="maps-widget">
     
      <div class="header">
       <h4>Find Us</h4>
      </div>
      
      <figure>
          <iframe height="250" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3489.6465289478997!2d-49.7620933851515!3d-28.997843582275124!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95221ebe8765c7db%3A0xef9e2ee8f35a8f83!2sJacinto+Machado!5e0!3m2!1spt-BR!2sbr!4v1470938958318" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
       </figure>
     
     </div>
    </div> <!-- End Widget -->
  
   </div> <!-- End Sidebar -->
  
  </div> <!-- End Row-Fluid -->
  <script type="text/javascript" src="/Portal_city556622/stretched/js/contato.js"></script>