<div class="row-fluid">
    <div id="main" class="span8 blog-posts image-preloader">

        <div class="row-fluid">
            <?php
            $categorias['title']="";
            if (empty($this->id)):
                //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
                $empresas=$this->HomeHelper()->ExeRead("bs_empresas", " WHERE catid=?  AND (title like ? OR description like ?) ORDER BY created DESC",[$this->action,"%{$this->filtro['search']}%","%{$this->filtro['search']}%"]);
                $categorias['title']="Todas As Cidades";
                else:
                $empresas=$this->HomeHelper()->ExeRead("bs_empresas", " WHERE catid=? AND cidade=?  AND (title like ? OR description like ?) ORDER BY created DESC",[$this->action,$this->id,"%{$this->filtro['search']}%","%{$this->filtro['search']}%"]);
                $categorias['title']=$this->HomeHelper()->getCidade($this->id);
            endif;
            $breadcrumb = $this->partial('/tpl/breadcrumb');
            $categorias['categoria']=$this->HomeHelper()->getCategorias($this->action);
            $categorias['url']="";
            echo $this->HomeHelper()->Show($categorias, $breadcrumb,$this->action);
            echo $this->partial('/tpl/search',['result'=>$empresas,'url'=>$this->url($this->route,['action'=>$this->action,'id'=>$this->id]),'filtro'=>$this->filtro]);

            if (!$empresas->getResult()):
                $this->HomeHelper()->alert($empresas->getError());
                else:
                  ?>
                <div class="sep-border margin-bottom30"></div> <!-- Sep Border -->
                <?php
                $html=[];
                if (!$empresas->getResult()):
                    $this->HomeHelper()->alert($empresas->getError());
                else:
                    $post_list = $this->partial('/tpl/empresas/empresas-list');
                    foreach ($empresas->getData() as $empresa):
                        $empresa['categoria']=$this->HomeHelper()->getCategorias($empresa['catid']);
                        $html[]=$this->HomeHelper()->Show($empresa, $post_list,'empresa');
                    endforeach;
                    echo implode(PHP_EOL,$html);
                endif;
            endif;
            ?>
            <nav class="nav-pagination">
                <?php
                if (!$empresas->getResult()):
                echo $this->paginationControl(
                    $empresas->getData(),
                    'Sliding',
                    '/widget/paginator',
                    ['route' => $this->route,
                        'action'=>$this->action,
                        'id'=>$this->id?$this->id:0]
                );
                echo $this->Html('p')->setText("Pagina")->appendText($this->page)->appendText(" a ")->appendText('10')->appendText(" de ")->appendText($empresas->getResult());
               endif;
                ?>
            </nav> <!-- End Nav-Pagination -->

        </div> <!-- End Row-Fluid -->

    </div> <!-- End Main -->

    <div id="sidebar" class="span4">
         <div class="widget clearfix">
            <?php echo $this->partial('/widget/enews-tabs'); ?>
        </div>
        <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/sponsors'); ?>
        </div> <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/subscribe-form'); ?>
        </div> <!-- End Widget -->


    </div> <!-- End Sidebar -->

</div> <!-- End Row-Fluid -->