<div class="row-fluid">
    <div id="main" class="span12 page author-page image-preloader">
        <div class="row-fluid">
            <div class="author-bio clearfix">
                <figure><img id="user-preview" alt="<?=$this->user->title?>" src="/dist/<?=$this->user->images?>" ></figure>
                <div class="content">
                    <h3><?=$this->user->title?></h3>
                    <p><?=$this->user->description?></p>
                    <p class="add-info"><i class="icon-share"></i> Email: <a title="Send a private message via email" href="#"><?=$this->user->email?></a></p>
                </div>
            </div> <!-- End Author-Bio -->
            <?php

            $this->HomeHelper()->setSelect(" count(id) as result ");
            $encontrou=$this->HomeHelper()->ExeRead("bs_classificados",' WHERE  created_by=?',[$this->user->id],true);
            $this->HomeHelper()->setSelect(" * ");
            $count="0";
            if($encontrou->getResult()){
                $count=$encontrou->getData()['result'];
            }
            ?>
            <?php echo $this->partial('/widget/minha-conta-tabs'); ?>
           <!-- One -->
           <div class="clearfix ie-sep"></div> <!-- Clearfix -->
        </div> <!-- End Row-Fluid -->
    </div> <!-- End Main -->
 </div> <!-- End Row-Fluid -->