<?php
$tpl=$this->partial('/widget/minha-empresa-form');
echo $this->HomeHelper()->formMinhaEmpresa($tpl);
?>
<script>
    $(function(){

        var options= {
            beforeSubmit: showComentRequest,  // pre-submit callback
            success: showComentResponse,  // post-submit callback
            type: 'post',        // 'get' or 'post', override for form's 'method' attribute
            dataType: 'json'
        };
        // bind to the form's submit event
        $("#Empresas").ajaxForm(options);

        $("#cidade").change(function(){
            $.ajax({
                url:'/cidadeonline/getuf/'+$(this).val(),
                dataType:'json',
                success:function(data){
                console.log(data);
                $("#uf").val(data.uf);
                }
              
            });
        })
    })
    // pre-submit callback
    function showComentRequest(formData, jqForm, options) {
        $('#output').addClass('alert alert-info').html('Enviando...');
        return true;
    }

    // post-submit callback
    function showComentResponse(responseText, statusText, xhr, $form)  {

        $('#output').removeClass('alert alert-info');
        if(responseText.result==true){
            $('#output').addClass('alert alert-success');
            $("#id").val(responseText.data.id);
            $("#codigo").val(responseText.data.codigo);
            $("#asset_id").val(responseText.data.asset_id);

        }
        else{
            $('#output').addClass('alert alert-danger');
        }
        $('#output').html(responseText.error);
    }
</script>
