<div class="row-fluid">
    <div id="main" class="span10 offset1 page author-page image-preloader">
        <div class="row-fluid">
            <?php
            $tpl=$this->partial('/widget/novo-anuncio-form');
            echo $this->HomeHelper()->formNovoAnuncio($tpl);
            ?>
            <div class="clearfix ie-sep"></div> <!-- Clearfix -->
            <div id="output"></div>
        </div> <!-- End Row-Fluid -->
    </div> <!-- End Main -->
</div> <!-- End Row-Fluid -->
<script src="/Portal_city556622/stretched/js/minhaconta.js"></script>