<div class="row-fluid">
    <div class="span8 page image-preloader" id="main">
        <div class="row-fluid">
            <h3>TIRE SUAS DUVIDADS</h3>
            <p><h4>Quanto custa Para Anunciar No Portal?</h4></p><br>
            <blockquote>Quisque placerat erat ac nunc consequat faucibus. Aenean tortor purus, faucibus a varius nec, facilisis vel enim. Maecenas quis felis ante. Aenean vulputate, risus a porta porta, sapien lectus euismod nisi, ut dapibus felis ante quis diam. Morbi velit tortor, adipiscing vel auctor nec, malesuada a risus.<small>Dots Theme Owner, <cite title="Mugiwara Kiwolen">Mugiwara Kiwolen</cite></small></blockquote><br>

            <p><h4>Quanto custa Para Anunciar No Portal?</h4></p><br>
            <blockquote>Quisque placerat erat ac nunc consequat faucibus. Aenean tortor purus, faucibus a varius nec, facilisis vel enim. Maecenas quis felis ante. Aenean vulputate, risus a porta porta, sapien lectus euismod nisi, ut dapibus felis ante quis diam. Morbi velit tortor, adipiscing vel auctor nec, malesuada a risus.<small>Dots Theme Owner, <cite title="Mugiwara Kiwolen">Mugiwara Kiwolen</cite></small></blockquote><br>

            <p><h4>Quanto custa Para Anunciar No Portal?</h4></p><br>
            <blockquote>Quisque placerat erat ac nunc consequat faucibus. Aenean tortor purus, faucibus a varius nec, facilisis vel enim. Maecenas quis felis ante. Aenean vulputate, risus a porta porta, sapien lectus euismod nisi, ut dapibus felis ante quis diam. Morbi velit tortor, adipiscing vel auctor nec, malesuada a risus.<small>Dots Theme Owner, <cite title="Mugiwara Kiwolen">Mugiwara Kiwolen</cite></small></blockquote><br>

            <p><h4>Quanto custa Para Anunciar No Portal?</h4></p><br>
            <blockquote>Quisque placerat erat ac nunc consequat faucibus. Aenean tortor purus, faucibus a varius nec, facilisis vel enim. Maecenas quis felis ante. Aenean vulputate, risus a porta porta, sapien lectus euismod nisi, ut dapibus felis ante quis diam. Morbi velit tortor, adipiscing vel auctor nec, malesuada a risus.<small>Dots Theme Owner, <cite title="Mugiwara Kiwolen">Mugiwara Kiwolen</cite></small></blockquote><br>

            <p><h4>Quanto custa Para Anunciar No Portal?</h4></p><br>
            <blockquote>Quisque placerat erat ac nunc consequat faucibus. Aenean tortor purus, faucibus a varius nec, facilisis vel enim. Maecenas quis felis ante. Aenean vulputate, risus a porta porta, sapien lectus euismod nisi, ut dapibus felis ante quis diam. Morbi velit tortor, adipiscing vel auctor nec, malesuada a risus.<small>Dots Theme Owner, <cite title="Mugiwara Kiwolen">Mugiwara Kiwolen</cite></small></blockquote><br>
            <div class="clearfix ie-sep"></div> <!-- Clearfix -->
        </div> <!-- End Row-Fluid -->
    </div> <!-- End Main -->

    <div id="sidebar" class="span4">

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/enews-tabs'); ?>
        </div>
        <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/sponsors'); ?>
        </div> <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/subscribe-form'); ?>
        </div> <!-- End Widget -->



    </div> <!-- End Sidebar -->

</div> <!-- End Row-Fluid -->
