
<div class="row-fluid">
<div id="main" class="span8 single single-post image-preloader">

<div class="row-fluid">
<?php
$this->HomeHelper()->setSelect(" a.*,c.title as autor,c.images as foto_autor,c.url as url_autor,c.description as desc_autor,g.title as categoria,g.url as url_cat ");
                                    //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
$posts=$this->HomeHelper()->ExeRead("bs_posts a", " ,bs_users c, bs_categorias g WHERE a.created_by=c.id AND a.catid=g.id AND a.url=?", [$this->id],true);
$this->HomeHelper()->setSelect(" * ");
if (!$posts->getResult()):
    $this->HomeHelper()->alert($posts->getError());
endif;
?>
<?php
if ($posts->getResult()):
    $breadcrumb = $this->partial('/tpl/breadcrumb');
    $emp=$posts->getData();
    $emp['url']=$emp["url_cat"];
    echo $this->HomeHelper()->Show($emp, $breadcrumb,"blog-posts");
 endif;
 ?>

<?php
if ($posts->getResult()):
    $post_figure = $this->partial('/tpl/posts/posts-figure');
    echo $this->HomeHelper()->Show($posts->getData(), $post_figure,"blog-posts");
 endif;
 ?>
<div class="content">
<?php
if ($posts->getResult()):
   echo $this->HomeHelper()->Show($posts->getData(), "#description#","blog-posts",500,10000);
 endif;
 ?>

</p>

    <div class="tags">
        <strong>Tags:</strong>&nbsp;
       <?php $cats=$this->HomeHelper()->ExeRead("bs_categorias", " WHERE state=0  AND parent_id<>'' ORDER BY id DESC");
       if ($cats->getResult()):
           $tag_categorias = $this->partial('/tpl/tag-categorias');
           foreach ($cats->getData() as $cat) {
               echo   $this->HomeHelper()->Show($cat, $tag_categorias,"blog-posts");
           }
       endif;
       ?>
    </div> <!-- End Tags -->

</div> <!-- End Content -->

<div class="sep-border"></div> <!-- Separator -->

<div class="post-author clearfix">
    <?php
    if ($posts->getResult()):
        $autor=$posts->getData();
         echo $this->HomeHelper()->Show($autor, $this->partial('/tpl/autor-post'),"blog-autor",12,38,'url_autor');
    endif;
    ?>
</div> <!-- End Post Author -->

<div class="sep-border no-margin-bottom"></div> <!-- Separator -->

<div class="prevnext-posts clearfix">
    <?php
    if ($posts->getResult()):
        $postId=$posts->getData();
        $navigation=$this->HomeHelper()->ExeRead("bs_posts", " WHERE id<? LIMIT 1", [$postId['id']],true);
        if($navigation->getResult()){
            $navprev=$navigation->getData();
            $navprev['desc']=$navprev['title'];
            echo $this->HomeHelper()->Show($navprev, $this->partial('/tpl/prev',['prev'=>"Postagem Anterior"]),"posts",5,38);
        }
      endif;
    if ($posts->getResult()):
        $postId=$posts->getData();
        $navigation=$this->HomeHelper()->ExeRead("bs_posts", " WHERE id>? LIMIT 1", [$postId['id']],true);
        if($navigation->getResult()){
            $navnext=$navigation->getData();
            $navnext['desc']=$navnext['title'];
            echo $this->HomeHelper()->Show($navnext, $this->partial('/tpl/next',['next'=>"Proxima Postagem"]),"posts",5,38);
        }
      endif;
    ?>

</div> <!-- End PrevNext-Posts -->

<div class="sep-border no-margin-top"></div> <!-- Separator -->

<div class="related-posts">
    <h3>Related Posts</h3>
    <?php
    if ($posts->getResult()):
        $postId=$posts->getData();
        //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
        $postsRelated=$this->HomeHelper()->ExeRead("bs_posts", " WHERE catid=? AND id<>? ORDER BY id DESC LIMIT 4", [$postId['catid'],$postId['id']]);
        $this->HomeHelper()->setSelect(" * ");
        $html=[];
        if (!$postsRelated->getResult()):
            $this->HomeHelper()->alert($postsRelated->getError());
        else:
            $nomargin=" no-margin-left";
            foreach ($postsRelated->getData() as $post):
                $post['nomargin']=$nomargin;
                $html[]=$this->HomeHelper()->Show($post, $this->partial('/widget/related-post'),"posts",5);
                $nomargin="";

            endforeach;

            echo implode(PHP_EOL,$html);
        endif;
    endif;
      ?>


</div> <!-- End Related-Posts -->

<div class="sep-border"></div> <!-- Separator -->

<div id="comments">
    <div id="load-comments">

    </div>
    <?php
    if($this->user):
        $data['title']=$postId['title'];
        $data['html']=$this->partial('/widget/comments-form');
        $data['parent_id']=$postId['id'];
        $data['parent']='post';
        $data['tipo']='0';
        $data['id_form']="Comentarios";
      echo  $this->HomeHelper()->formComentarios($data);
    else:?>
        <div class="alert alert-warning">
        	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        	<strong>OPPSS!</strong> Somente Usuarios Logados Podem Comentar
        </div>
   <?php endif; ?>
</div> <!-- End Comments -->

</div> <!-- End Row-Fluid -->
</div> <!-- End Main -->

<div id="sidebar" class="span4">

    <div class="widget clearfix">
       <?php echo $this->partial('/tpl/social-indices'); ?>
    </div> 
    <!-- End Widget -->
    
    <div class="widget clearfix">
    <?php echo $this->partial('/widget/enews-tabs'); ?>
    </div> 
    <!-- End Widget -->

<div class="widget clearfix">
    <?php echo $this->partial('/widget/sponsors'); ?>
</div> <!-- End Widget -->

<div class="widget clearfix">
   <?php echo $this->partial('/widget/subscribe-form'); ?>
</div> <!-- End Widget -->



</div> <!-- End Sidebar -->

</div> <!-- End Row-Fluid -->
<?php
if ($posts->getResult()):
    $postId=$posts->getData();
    ?>
    <script type="text/javascript" src="/Portal_city556622/stretched/js/comments.js"></script>
<script>
    $(function(){
        var conteudo=$('#load-comments');
        conteudo.load('<?=$this->url('cidadeonline-pages', array('controller' => 'cidadeonline', 'action' => 'loadcommentsposts','id'=>$postId['id']))?>');

    })
</script>
<?php endif;?>