<div class="row-fluid">
    <div id="main" class="span8 blog-posts image-preloader">

        <div class="row-fluid">

            <?php
            $categorias['title']="";
            //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
            $autor=$this->HomeHelper()->ExeRead("bs_users", " WHERE url=?", [$this->id],true);
            //SE EXISTIR UMA CATEGORIA LISTA OS POSTS DA CATEGORIA SELECIONADA
            if (!$autor->getResult()):
                $this->HomeHelper()->alert($autor->getError());
                $posts=$autor;
            else:
                //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
                $this->HomeHelper()->setSelect(" a.*,g.title as categoria ");
                //tabela,estraselect,params,bool[true=1 registro ou false uma lista]
                $posts=$this->HomeHelper()->ExeRead("bs_posts a", " , bs_categorias g WHERE a.catid=g.id AND a.created_by=?   AND (a.title like ? OR a.description like ?) ORDER BY a.created DESC", [$autor->getData()['id'],"%{$this->filtro['search']}%","%{$this->filtro['search']}%"]);
                $this->HomeHelper()->setSelect(" * ");
                $categorias['title']=$autor->getData()['title'];
            endif;
            $breadcrumb = $this->partial('/tpl/breadcrumb');
            $categorias['categoria']="Posts Autor";
            echo $this->HomeHelper()->Show($categorias, $breadcrumb,"posts");
            echo $this->partial('/tpl/search',['result'=>$posts,'url'=>$this->url($this->route,['action'=>$this->action,'id'=>$this->id]),'filtro'=>$this->filtro]);
            ?>
            <div class="sep-border margin-bottom30"></div> <!-- Sep Border -->
            <?php
            $html=[];
            if (!$autor->getResult()):
                $this->HomeHelper()->alert($autor->getError());
            else:
                $post_list = $this->partial('/tpl/posts/posts-list');
                foreach ($posts->getData() as $post):
                    $post['autor']=$autor->getData()['title'];
                    $html[]=$this->HomeHelper()->Show($post, $post_list,"posts");
                endforeach;
                echo implode(PHP_EOL,$html);
            endif;

            ?>
            <!-- Four -->

            <nav class="nav-pagination">
                <?php
                if ($posts->getResult()):
                echo $this->paginationControl(
                    $posts->getData(),
                    'Sliding',
                    '/widget/paginator',
                    ['route' => $this->route,
                        'action'=>$this->action,
                        'id'=>$this->id?$this->id:0]
                );
                echo $this->Html('p')->setText("Pagina")->appendText($this->page)->appendText(" a ")->appendText('10')->appendText(" de ")->appendText($posts->getResult());
               endif;
                ?>
            </nav> <!-- End Nav-Pagination -->

        </div> <!-- End Row-Fluid -->

    </div> <!-- End Main -->

    <div id="sidebar" class="span4">
        <div class="widget clearfix">
            <?php echo $this->partial('/widget/enews-tabs'); ?>
        </div>
        <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/sponsors'); ?>
        </div> <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/subscribe-form'); ?>
        </div> <!-- End Widget -->


    </div> <!-- End Sidebar -->

</div> <!-- End Row-Fluid -->