<?php
$cache=$this->CacheHelper();
$issusers=$cache->getItem('issusers');
$dadosCidade=$this->HomeHelper()->getDadosCidade($issusers['municipio']);
$issusers['city']=$dadosCidade['title'];
?>
<div class="row-fluid">
    <div id="main" class="span8 single single-post image-preloader">
        <div class="row-fluid">

<?php echo $this->HomeHelper()->Show($issusers, $this->partial('/tpl/termos'),"posts-list"); ?>

        <div class="clearfix ie-sep"></div> <!-- Clearfix -->
        </div> <!-- End Row-Fluid -->
    </div> <!-- End Main -->

    <div id="sidebar" class="span4">

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/enews-tabs'); ?>
        </div>
        <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/sponsors'); ?>
        </div> <!-- End Widget -->

        <div class="widget clearfix">
            <?php echo $this->partial('/widget/subscribe-form'); ?>
        </div> <!-- End Widget -->



    </div> <!-- End Sidebar -->

</div> <!-- End Row-Fluid -->
