<?php
$form = $this->form;
$form->setAttribute('action', $this->url($this->route, array('controller' => $this->controller, 'action' => 'finaliza')));
$this->formElementErrors()
    ->setMessageOpenFormat('<ul class="nav"><li class="erro-obrigatorio">')
    ->setMessageSeparatorString('</li>')->render($form);
echo $this->form()->openTag($form);
$this->GerarViewHelper()->GerarElement($form);
if(!is_dir("./module_rest/Admin/view/admin/admin/tpl/{$this->controller}")):
    mkdir("./module_rest/Admin/view/admin/admin/tpl/{$this->controller}");
endif;
if (!$this->resolver("admin/admin/tpl/{$this->controller}/inserir")) :
    file_put_contents("./module_rest/Admin/view/admin/admin/tpl/{$this->controller}/inserir.phtml", $this->GerarViewHelper()->formGrupo());
endif;
$html = $this->partial("admin/admin/tpl/{$this->controller}/inserir");
$primeiro = str_replace(array_keys($this->GerarViewHelper()->getHtml()), array_values($this->GerarViewHelper()->getHtml()), $html);
echo str_replace(array_keys($this->GerarViewHelper()->getLabels()), array_values($this->GerarViewHelper()->getLabels()), $primeiro);
echo $this->form()->closeTag();