<div class="col-md-3&#x20;col-sm-6&#x20;col-xs-12&#x20;col-box-list">
    <div class="pricing">
        <div class="title">
            <h1>{{title}}</h1>
        </div>
        <div class="x_content">
            <div>
                <div class="pricing_features">
                    <ul class="list-unstyled&#x20;text-left">
                        <li>{{images}}</li>
                        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
                            <strong>{{agencia}}</strong></li>
                        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
                            <strong>{{carteira}}</strong></li>
                        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
                            <strong>{{conta}}</strong></li>
                        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
                            <strong>{{sequencial}}</strong></li>
                        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
                            <strong>{{conta_dv}}</strong></li>
                        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
                            <strong>{{agencia_dv}}</strong></li>
                        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
                            <strong>{{descricao_demonstrativo}}</strong></li>
                        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
                            <strong>{{instrucoes}}</strong></li>
                        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
                            <strong>{{description}}</strong></li>

                        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
                            <strong>{{state}}</strong></li>
                        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
                            <strong>{{created}}</strong></li>
                        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
                            <strong>{{modified}}</strong></li></ul></div></div>
            <div class="pricing_footer">
                {{buttons}}
            </div>
        </div>
    </div></div>