<?= $this->doctype() ?>
<html lang="pb-br">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF BASE')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');?>
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/floatexamples.css'))
                        ->prependStylesheet($this->basePath('css/icheck/flat/green.css'))
                        ->prependStylesheet($this->basePath('css/custom.css'))
                        ->prependStylesheet($this->basePath('css/animate.min.css'))
                        ->prependStylesheet($this->basePath('fonts/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
    </head>
        <body  style="background:#F7F7F7;">
            <div class="">
                <div id="wrapper">
                    <?=$this->content; ?>
                </div>
            </div>
            <!-- Scripts -->
            <?= $this->headScript()
                ->prependFile($this->basePath('js/custom.js'))
                ->prependFile($this->basePath('js/nprogress.js'))
                ->prependFile($this->basePath('js/icheck/icheck.min.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))?>
            <?= $this->inlineScript() ?>
        </body>
</html>
