<?= $this->doctype() ?>
<html lang="pb-br">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Cidade Online')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');?>
    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/floatexamples.css'))
        ->prependStylesheet($this->basePath('/_cdn/css/style.css'))
        ->prependStylesheet($this->basePath('fonts/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('/_cdn/css/reset.css'))
    ?>
</head>
<body>
<?=$this->partial('/partials/inc/header');?>
<?=$this->content; ?>
<?=$this->partial('/partials/inc/footer');?>
<!-- Scripts -->
<?= $this->headScript()
    ->prependFile($this->basePath('/_cdn/js/combo.js'))
    ->prependFile($this->basePath('/_cdn/js/_scripts.conf.js'))
    ->prependFile($this->basePath('/_cdn/js/_plugins.conf.js'))
    ->prependFile($this->basePath('/_cdn/js/shadowbox/shadowbox.js'))
    ->prependFile($this->basePath('/_cdn/js/jmask.js'))
    ->prependFile($this->basePath('/_cdn/js/jcycle.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))?>
<?= $this->inlineScript() ?>
</body>
</html>
