<div class="col-md-3&#x20;col-sm-6&#x20;col-xs-12&#x20;col-box-list">
<div class="pricing">
<div class="title">
<h1>{{title}}</h1>
</div>
<div class="x_content">
<div>
<div class="pricing_features">
    <ul class="list-unstyled&#x20;text-left">
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{fantasia}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{logradouro}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{numero}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{complemento}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{municipio}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{uf}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{cep}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{images}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{cnpj}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{ie}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{im}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{cnae}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{csc}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{csc_id}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{ibpt}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{email}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{pass}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{smtp}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{port}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{ssl}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{fromname}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{replyto}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{state}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{created}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{modified}}</strong></li></ul>
</div></div>
<div class="pricing_footer">
{{buttons}}
</div>
</div>
</div></div>