<fildset>
    <legend>FORMULARIO DE MANUTENÇÃO</legend>
    <div class="col-md-8 col-xs-12">
        <div class="x_panel">

            <div class="x_content">
                <fieldset>
                    <legend>DADOS GERAIS DO EMITENTE</legend>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{fantasia}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                            #fantasia#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{title}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                            #title#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{phone}}');?></div><div class="col-md-7 col-sm-9 col-xs-12">
                            #phone#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{cnpj}}');?></div><div class="col-md-7 col-sm-9 col-xs-12">
                            #cnpj#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{ie}}');?></div><div class="col-md-4 col-sm-9 col-xs-12">
                            #ie#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{im}}');?></div><div class="col-md-4 col-sm-9 col-xs-12">
                            #im#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{cnae}}');?></div><div class="col-md-3 col-sm-9 col-xs-12">
                            #cnae#</div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{ibpt}}');?></div><div class="col-md-5 col-sm-9 col-xs-12">
                            #ibpt#</div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{csc}}');?></div><div class="col-md-7 col-sm-9 col-xs-12">
                            #csc#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{csc_id}}');?></div><div class="col-md-4 col-sm-9 col-xs-12">
                            #csc_id#</div>
                    </div>
                </fieldset>
                <fieldset>
                    <legend>ENDEREÇO DO EMITENTE</legend>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{uf}}');?></div><div class="col-md-3 col-sm-9 col-xs-12">
                            #uf#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{municipio}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                            #municipio#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{cep}}');?></div><div class="col-md-4 col-sm-9 col-xs-12">
                            #cep#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{logradouro}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                            #logradouro#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{numero}}');?></div><div class="col-md-4 col-sm-9 col-xs-12">
                            #numero#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{complemento}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                            #complemento#</div>
                    </div>

                </fieldset>
                <fieldset>
                    <legend>INFORMAÇÕES DE CONTATO DO EMITENTE</legend>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{email}}');?></div><div class="col-md-9 col-sm-9 col-xs-12">
                            #email#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{fromname}}');?></div><div class="col-md-8 col-sm-9 col-xs-12">
                            #fromname#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{replyto}}');?></div><div class="col-md-8 col-sm-9 col-xs-12">
                            #replyto#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{smtp}}');?></div><div class="col-md-7 col-sm-9 col-xs-12">
                            #smtp#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{ssl}}');?></div><div class="col-md-5 col-sm-9 col-xs-12">
                            #ssl#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{port}}');?></div><div class="col-md-3 col-sm-9 col-xs-12">
                            #port#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{pass}}');?></div><div class="col-md-4 col-sm-9 col-xs-12">
                            #pass#</div>
                    </div>
                </fieldset>


                #id##codigo##empresa##asset_id##security#</div>
            <div class="box-footer">
                <div class="pull-right">
                    #save##btn-voltar#
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-xs-12">
        <div class="x_panel">
            <div class="x_title box-default">
                <h2 class="x_title"><small>IMAGENS</small></h2>
                <div class="clearfix"></div></div>
            <div class="x_content">
                <div class="img-add "><?php echo $this->translate('{{images}}');?>#imagePreview#</div>
                <div class="row">
                    <div class="input-group class-file">
                        <div class="btn btn-primary btn-file"><i class="ion ion-android-upload"></i>
                            <span class="file-text">Selecione uma imagem</span>
                            <input name="attachment" type="file" id="attachment" />#images#</div><p class="help-block">Max. 32MB</p></div>
                    <div class="clear"></div>
                </div></div>

        </div>

        <div class="x_panel">

            <div class="x_content">
                <fieldset>
                    <legend>GERAL</legend>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{access}}');?></div><div class="col-md-8 col-sm-9 col-xs-12">
                            #access#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{state}}');?></div><div class="col-md-8 col-sm-9 col-xs-12">
                            #state#</div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{created}}');?></div><div class="col-md-8 xdisplay_inputx form-group has-feedback">
                            #created#<span class="fa fa-calendar-o form-control-feedback right"></span></div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12" for="">
                            <?php echo $this->translate('{{modified}}');?></div><div class="col-md-8 xdisplay_inputx form-group has-feedback">
                            #modified#<span class="fa fa-calendar-o form-control-feedback right"></span></div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            #description#</div>
                    </div>
                </fieldset>
            </div>

        </div>
    </div>
</fildset>
<script src="/js/tinymce/tinymce.min.js" type="text/javascript"></script>
<script src="/js/tinymce.init.js" type="text/javascript"></script>
<script>
    intTinymce("#description");
</script>