<fildset>
<legend>FORMULARIO DE MANUTENÇÃO</legend>
<div class="col-md-8&#x20;col-xs-12">
<div class="x_panel">

<div class="x_content">
    <fieldset>
        <legend>DADOS GERAIS DO EMITENTE</legend>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{fantasia}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #fantasia#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{title}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #title#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{cnpj}}');?></div><div class="col-md-7&#x20;col-sm-9&#x20;col-xs-12">
            #cnpj#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{ie}}');?></div><div class="col-md-4&#x20;col-sm-9&#x20;col-xs-12">
            #ie#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{im}}');?></div><div class="col-md-4&#x20;col-sm-9&#x20;col-xs-12">
            #im#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{cnae}}');?></div><div class="col-md-3&#x20;col-sm-9&#x20;col-xs-12">
            #cnae#</div>
    </div>

    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{ibpt}}');?></div><div class="col-md-5&#x20;col-sm-9&#x20;col-xs-12">
            #ibpt#</div>
    </div>

    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{csc}}');?></div><div class="col-md-7&#x20;col-sm-9&#x20;col-xs-12">
            #csc#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{csc_id}}');?></div><div class="col-md-4&#x20;col-sm-9&#x20;col-xs-12">
            #csc_id#</div>
    </div>
        </fieldset>
    <fieldset>
        <legend>ENDEREÇO DO EMITENTE</legend>
        <div class="form-group">
            <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                <?php echo $this->translate('{{uf}}');?></div><div class="col-md-3&#x20;col-sm-9&#x20;col-xs-12">
                #uf#</div>
        </div>
        <div class="form-group">
            <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                <?php echo $this->translate('{{municipio}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
                #municipio#</div>
        </div>
        <div class="form-group">
            <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                <?php echo $this->translate('{{cep}}');?></div><div class="col-md-4&#x20;col-sm-9&#x20;col-xs-12">
                #cep#</div>
        </div>
        <div class="form-group">
            <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                <?php echo $this->translate('{{logradouro}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
                #logradouro#</div>
        </div>
        <div class="form-group">
            <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                <?php echo $this->translate('{{numero}}');?></div><div class="col-md-4&#x20;col-sm-9&#x20;col-xs-12">
                #numero#</div>
        </div>
        <div class="form-group">
            <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                <?php echo $this->translate('{{complemento}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
                #complemento#</div>
        </div>

    </fieldset>
    <fieldset>
        <legend>INFORMAÇÕES DE CONTATO DO EMITENTE</legend>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{email}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #email#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{fromname}}');?></div><div class="col-md-8&#x20;col-sm-9&#x20;col-xs-12">
            #fromname#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{replyto}}');?></div><div class="col-md-8&#x20;col-sm-9&#x20;col-xs-12">
            #replyto#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{smtp}}');?></div><div class="col-md-7&#x20;col-sm-9&#x20;col-xs-12">
            #smtp#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{ssl}}');?></div><div class="col-md-5&#x20;col-sm-9&#x20;col-xs-12">
            #ssl#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{port}}');?></div><div class="col-md-3&#x20;col-sm-9&#x20;col-xs-12">
            #port#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{pass}}');?></div><div class="col-md-4&#x20;col-sm-9&#x20;col-xs-12">
            #pass#</div>
    </div>
    </fieldset>


#id##codigo##empresa##asset_id##security##images#</div>
<div class="box-footer">
<div class="pull-right">
    #save##btn-voltar#
</div>
</div>
</div>
</div>
<div class="col-md-4&#x20;col-xs-12">
<div class="x_panel">

<div class="x_content">
    <fieldset>
        <legend>GERAL</legend>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{access}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #access#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{state}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
            #state#</div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{created}}');?></div><div class="col-md-8&#x20;xdisplay_inputx&#x20;form-group&#x20;has-feedback">
            #created#<span class="fa&#x20;fa-calendar-o&#x20;form-control-feedback&#x20;right"></span></div>
    </div>
    <div class="form-group">
        <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
            <?php echo $this->translate('{{modified}}');?></div><div class="col-md-8&#x20;xdisplay_inputx&#x20;form-group&#x20;has-feedback">
            #modified#<span class="fa&#x20;fa-calendar-o&#x20;form-control-feedback&#x20;right"></span></div>
    </div>
        <div class="form-group">
            <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                <?php echo $this->translate('{{description}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
                #description#</div>
        </div>
        </fieldset>
</div>

</div>
</div>
</fildset>