<li>
<a>
  <span class="image">
                <img alt="#title#" src="/dist/tim.php?src=/dist/#images#&w=120&h=120">
            </span>
  <span>
                <span>#title#</span>
  <span class="time">#data# - #hora#</span>
  </span>
  <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where you met the producers that
            </span>
</a>
</li>