<div class="x_panel fixed_height_390">
  <div class="x_content">

    <div class="flex">
      <ul class="list-inline widget_profile_box name">
        <li>
          <a>
            <i class="fa fa-facebook"></i>
          </a>
        </li>
        <li>
          <img class="img-circle profile_img" alt="#title#" src="/dist/tim.php?src=/dist/#images#&w=120&h=120">
        </li>
        <li>
          <a>
            <i class="fa fa-twitter"></i>
          </a>
        </li>
      </ul>
    </div>

    <h3 class="name">#title#</h3>

    <div class="flex">
      <ul class="list-inline count2">
        <li>
          <h4 id="tot-posts-#id#">#posts#</h4>
          <span>Posts</span>
        </li>
        <li>
          <h4 id="tot-classificados-#id#">#classificados#</h4>
          <span>Classif.</span>
        </li>
        <li>
          <h4 id="tot-empresas-#id#">#empresas#</h4>
          <span>Empresas</span>
        </li>
      </ul>
    </div>
      <div class="flex">
          <ul class="list-inline count2">
              <li>
                  <h6 id="tot-posts-#id#">#ip#</h6>
                  <span>Ip</span>
              </li>
              <li>
                  <h6 id="tot-posts-#id#">#data#</h6>
                  <span>Data</span>
              </li>
               <li>
                  <h6 id="tot-empresas-#id#">#hora#</h6>
                  <span>Hora</span>
              </li>
          </ul>
      </div>
    <p id="pagina-atual-#id#">
      #url#
    </p>
  </div>
</div>
