     <?php
        $submit = $form->get('save');
        $submit->setValue($this->translate($submit->getValue()));
        $submit->setAttribute('class', 'btn btn-primary');
        ?>
        <div class="ln_solid"></div>
        <div class="form-group">
            <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                <a class="btn btn-danger" href="<?=$this->url($action)?>" >Cancel</a>
                <?=$this->formSubmit($submit) ?>
            </div>
        </div>
        <?php echo $this->form()->closeTag();?>

    </div>
</div>