<fildset>
    <legend>FORMULARIO DE MANUTENÇÃO</legend>
    <div class="col-md-8&#x20;col-xs-12">
        <div class="x_panel">

            <div class="x_content">
                <fieldset>
                    <legend>INFORMAÇÕES DO PRODUTO</legend>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{tipo}}');?></div><div class="col-md-5&#x20;col-sm-9&#x20;col-xs-12">
                        #tipo#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{title}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
                        #title#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{unidade}}');?></div><div class="col-md-4&#x20;col-sm-9&#x20;col-xs-12">
                        #unidade#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{catid}}');?></div><div class="col-md-6&#x20;col-sm-9&#x20;col-xs-12">
                        #catid#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{marca}}');?></div><div class="col-md-6&#x20;col-sm-9&#x20;col-xs-12">
                        #marca#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{estoque}}');?></div><div class="col-md-5&#x20;col-sm-9&#x20;col-xs-12">
                        #estoque#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{minimo}}');?></div><div class="col-md-5&#x20;col-sm-9&#x20;col-xs-12">
                        #minimo#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{peso}}');?></div><div class="col-md-4&#x20;col-sm-9&#x20;col-xs-12">
                        #peso#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{pago}}');?></div><div class="col-md-4&#x20;col-sm-9&#x20;col-xs-12">
                        #pago#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{lucro}}');?></div><div class="col-md-4&#x20;col-sm-9&#x20;col-xs-12">
                        #lucro#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{valor}}');?></div><div class="col-md-4&#x20;col-sm-9&#x20;col-xs-12">
                        #valor#</div>
                </div>
                </fieldset>
                <fieldset>
                    <legend>INFORMAÇÕES FISCAIS DO PRODUTO</legend>

                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{clfiscal}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
                        #clfiscal#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{cst}}');?></div><div class="col-md-7&#x20;col-sm-9&#x20;col-xs-12">
                        #cst#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{scfop}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
                        #scfop#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{ecfop}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
                        #ecfop#</div>
                </div>
                </fieldset>
                <fieldset>
                    <legend>DESCRIÇÃO DO PRODUTO</legend>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-3&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{description}}');?></div><div class="col-md-9&#x20;col-sm-9&#x20;col-xs-12">
                        #description#</div>
                </div>
                #id##codigo##empresa##asset_id##security##images#
                </fieldset>
            </div>
            <div class="box-footer">
                <div class="pull-right">
                    #save#<a class="btn btn-danger" href="/produtos/index/0/8">BTN_VOLTAR_LABEL</a><p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4&#x20;col-xs-12">
        <div class="x_panel">

            <div class="x_content">
                <fieldset>
                    <legend>INFORMAÇÕES ADICIONAIS DO PRODUTO</legend>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-4&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{access}}');?></div><div class="col-md-8&#x20;col-sm-9&#x20;col-xs-12">
                        #access#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-4&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{state}}');?></div><div class="col-md-8&#x20;col-sm-9&#x20;col-xs-12">
                        #state#</div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-4&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{created}}');?></div><div class="col-md-8&#x20;col-sm-9&#x20;col-xs-12 xdisplay_inputx&#x20;form-group&#x20;has-feedback">
                        #created#<span class="fa&#x20;fa-calendar-o&#x20;form-control-feedback&#x20;right"></span></div>
                </div>
                <div class="form-group">
                    <div class="control-label&#x20;col-md-4&#x20;col-sm-3&#x20;col-xs-12" for="&#x7B;&#x7B;&#x24;key&#x7D;&#x7D;">
                        <?php echo $this->translate('{{modified}}');?></div><div class="col-md-8&#x20;col-sm-9&#x20;col-xs-12 xdisplay_inputx&#x20;form-group&#x20;has-feedback">
                        #modified#<span class="fa&#x20;fa-calendar-o&#x20;form-control-feedback&#x20;right"></span></div>
                </div>
                </fieldset>
            </div>

        </div>
    </div>
</fildset>