
<div id="bottom">
    <div class="container">
        <div class="row-fluid">

            <div class="span3 widget clearfix">
                <div class="header">
                    <h4>About Us</h4>
                </div>

                <div class="content">
                    <p>Donec dignissim leo sit amet nisl luctus vestibulum. Morbi tortor arcu, aliquet nec aliquet at, convallis ut eros. Sed non tellus mauris, vitae congue ante.</p>
                    <p>Nunc imperdiet malesuada pharetra. Duis sodales, arcu tempus rutrum consectetur, sem ante auctor eros, in vehicula magna mauris sit amet est. Mauris ac eros arcu.</p>
                </div>
            </div> <!-- End Widget -->

            <div class="span3 widget clearfix">
                <div class="tags-cloud">

                    <div class="header">
                        <h4>Tags Cloud</h4>
                    </div>

                    <ul>
                        <li><a href="#">windows</a></li>
                        <li><a href="#">apple</a></li>
                        <li><a href="#">software</a></li>
                        <li><a href="#">hardware</a></li>
                        <li><a href="#">gadget</a></li>
                        <li><a href="#">smartphone</a></li>
                        <li><a href="#">laptop</a></li>
                        <li><a href="#">business</a></li>
                        <li><a href="#">learn</a></li>
                        <li><a href="#">study</a></li>
                        <li><a href="#">game</a></li>
                        <li><a href="#">movie</a></li>
                        <li><a href="#">event</a></li>
                    </ul>

                </div>
            </div> <!-- End Widget -->

            <div class="span3 widget clearfix">
                <div class="tweets">

                    <div class="header">
                        <h4>Latest Tweets</h4>
                    </div>

                    <ul>
                        <li>
                            <span class="picons"><!-- --></span>
                            <p><a href="#">@realt0rlife</a> That's a very good question :) You may want to contact the author. There's a form on the right when you click their name.</p>
                            <span class="date">- 10 hours ago</span>
                        </li>
                        <li>
                            <span class="picons"><!-- --></span>
                            <p><a href="#">@ghostpool</a> Have you opened a support ticket yet? Can you send methe ticket number? Thanks!</p>
                            <span class="date">- 2 days ago</span>
                        </li>
                    </ul>

                </div>
            </div> <!-- End Widget -->

            <div class="span3 widget clearfix">
                <div class="flickr-photos">

                    <div class="header">
                        <h4>Flickr Photos</h4>
                    </div>

                    <ul id="flickr-gallery"><!-- --></ul>

                </div>
            </div> <!-- End Widget -->

        </div> <!-- End Row-Fluid -->
    </div> <!-- End Container -->
</div> <!-- End Bottom -->

<div id="footer">
    <div class="container">

        <p class="pull-left">Copyright 2013 Dots Theme&nbsp;&nbsp;|&nbsp;&nbsp;All Rights Reserved&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#">Dots Theme</a></p>
        <ul class="social pull-right">
            <li><a href="#" title="Youtube"><img src="/Portal_city556622/stretched/images/social/f0101/youtube.png" alt="Youtube" /></a></li>
            <li><a href="#" title="LinkedIn"><img src="/Portal_city556622/stretched/images/social/f0101/linkedin.png" alt="LinkedIn" /></a></li>
            <li><a href="#" title="Vimeo"><img src="/Portal_city556622/stretched/images/social/f0101/vimeo.png" alt="Vimeo" /></a></li>
            <li><a href="#" title="Tumblr"><img src="/Portal_city556622/stretched/images/social/f0101/tumblr.png" alt="Tumblr" /></a></li>
            <li><a href="#" title="Flickr"><img src="/Portal_city556622/stretched/images/social/f0101/flickr.png" alt="Flickr" /></a></li>
            <li><a href="#" title="DeviantArt"><img src="/Portal_city556622/stretched/images/social/f0101/deviantart.png" alt="DeviantArt" /></a></li>
            <li><a href="#" title="Delicious"><img src="/Portal_city556622/stretched/images/social/f0101/delicious.png" alt="Delicious" /></a></li>
            <li><a href="#" title="Facebook"><img src="/Portal_city556622/stretched/images/social/f0101/facebook.png" alt="Facebook" /></a></li>
            <li><a href="#" title="Twitter"><img src="/Portal_city556622/stretched/images/social/f0101/twitter.png" alt="Twitter" /></a></li>
        </ul>

    </div> <!-- End Container -->
</div> <!-- End Footer -->

<a href="#" class="scrollup" title="Back to Top!">Scroll</a>

