<li><figure style="background-image:url(/dist/#images#);"></figure>

<a href="#url#" title="#title#"><div class="masked-hover"></div></a> <!-- Masked Hover -->
<div class="masked-base"></div> <!-- Masked Base -->
<div class="masked-color masked-violet"></div> <!-- Masked Color -->
<div class="text">
    <h2>#title#</h2>
    <span class="meta">By mdkiwol on #mes#". #dia#, #ano#</span>
    <p>#description#</p>
</div>
</li>