<li><figure style="background-image:url(/dist/tim.php?src=/dist/#images#&w=537&h=138);"></figure>
	<a href="#url#" title="#title#"><div class="masked-hover"></div></a> <!-- Masked Hover -->
	<div class="masked-base"></div> <!-- Masked Base -->
	<div class="masked-color masked-red"></div> <!-- Masked Color -->
	<div class="text">
	<h2>#title#</h2>
	<span class="meta">By jagerjack on #mes#. #dia#, #ano#</span>
	</div>
</li>
