
<div id="top-navigation">
    <div class="container">

        <!-- Navigation -->
        <ul class="nav-menu pull-left">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="#">CIDADE ONLINE</a>
                <div class="nav-sub-menu">
                    <ul class="container">
                        <li><a href="#">ACONTECEU</a></li>
                        <li><a href="#">EVENTOS</a></li>
                        <li><a href="#">ESPORTES</a></li>

                    </ul>
                </div>
            </li>
            <li><a href="#">ONDE COMPRAR</a></li>
            <li><a href="#">ONDE FICAR</a></li>
            <li><a href="#">ONDE SE DIVERTIR</a></li>
            <li><a href="#">CONTATO</a></li>
        </ul>

        <!-- Search Form -->
        <form name="form-search" method="post" action="/" class="form-search pull-right">
            <input type="text" name="search" placeholder="Search...." class="input-icon input-icon-search" />
        </form>

        <!-- Social Media -->
        <ul class="social pull-right">
            <li><a href="#" data-placement="bottom" data-original-title="Find us on LinkedIn"><img src="/Portal_city556622/stretched/images/social/infocus/linkedin-logo.png" alt="LinkedIn"></a></li>
            <li><a href="#" data-placement="bottom" data-original-title="Find us on Flickr"><img src="/Portal_city556622/stretched/images/social/infocus/flickr.png" alt="Flickr"></a></li>
            <li><a href="#" data-placement="bottom" data-original-title="Like us on Facebook"><img src="/Portal_city556622/stretched/images/social/infocus/facebook-logo.png" alt="Facebook"></a></li>
            <li><a href="#" data-placement="bottom" data-original-title="Follow on DeviantArt"><img src="/Portal_city556622/stretched/images/social/infocus/deviantart.png" alt="DeviantArt"></a></li>
            <li><a href="#" data-placement="bottom" data-original-title="Follow on Twitter"><img src="/Portal_city556622/stretched/images/social/infocus/twitter.png" alt="Twitter"></a></li>
            <li><a href="#" data-placement="bottom" data-original-title="Follow on Stumbleupon"><img src="/Portal_city556622/stretched/images/social/infocus/stumbleupon.png" alt="Stumbleupon"></a></li>
            <li><a href="#" data-placement="bottom" data-original-title="Call us via Skype"><img src="/Portal_city556622/stretched/images/social/infocus/skype.png" alt="Skype"></a></li>
        </ul>

    </div> <!-- End Container -->
</div> <!-- End Top-Navigation -->

<div class="container">
    <header id="header" class="clearfix">

        <!-- Logo -->
        <div class="logo pull-left">
            <a href="index-2.html"><img src="/Portal_city556622/stretched/images/logo.png" alt="Enews" /></a>
        </div>

        <!-- Ads -->
        <div class="ads pull-right">
            <img src="/Portal_city556622/stretched/images/ads/480x80.png" alt="Ads" />
        </div>

    </header> <!-- End Header -->

    <nav id="main-navigation" class="clearfix">
        <ul>
            <li><a href="#">NEGÓCIOs</a></li>
            <li><a href="#">TÉCNOLOGIA <i class="arrow-main-nav"></i></a>
                <ul>
                  <?php
                    $html=[];
                     $cat = $this->HomeHelper()->CatByName('tecnologia');
                     $post=$this->HomeHelper()->ExeRead("bs_categorias", "WHERE state =? AND parent_id=? ORDER BY id DESC LIMIT 3 OFFSET 0", ['0',$cat->getData()->id]);
                    if (!$post->getResult()):?>
                       <div class="alert alert-danger">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>OPSS!</strong><?=$post->getError()?>
                       </div>';
                     <?php  else:
                        foreach ($post->getData() as $slide):
                           $html[]=$this->HomeHelper()->Show($slide, '<li><a href="#url#">#title#</a></li>');
                        endforeach;
                    endif;
                    echo implode("", $html);
                    ?>
                                       
                </ul>
            </li>
              <li><a href="#">Entretenimento <i class="arrow-main-nav"></i></a>
                <ul>
                  <?php
                    $html=[];
                     $cat = $this->HomeHelper()->CatByName('entretenimento');
                     $post=$this->HomeHelper()->ExeRead("bs_categorias", "WHERE state =? AND parent_id=? ORDER BY id DESC LIMIT 3 OFFSET 0", ['0',$cat->getData()->id]);
                    if (!$post->getResult()):?>
                       <div class="alert alert-danger">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>OPSS!</strong><?=$post->getError()?>
                       </div>';
                     <?php  else:
                        foreach ($post->getData() as $slide):
                           $html[]=$this->HomeHelper()->Show($slide, '<li><a href="#url#">#title#</a></li>');
                        endforeach;
                    endif;
                    echo implode("", $html);
                    ?>
                                       
                </ul>
            </li>
            <li><a href="#">Education</a></li>
            <li><a href="#">Photo <i class="arrow-main-nav"></i></a>
                <ul>
                    <li><a href="#">Single Photo</a></li>
                </ul>
            </li>
            <li><a href="#">Video <i class="arrow-main-nav"></i></a>
                <ul>
                    <li><a href="#">Single Video</a></li>
                </ul>
            </li>
            <li><a href="#">Music <i class="arrow-main-nav"></i></a>
                <ul>
                    <li><a href="#">Single Music</a></li>
                </ul>
            </li>
            <li><a href="#">Review <i class="arrow-main-nav"></i></a>
                <ul>
                    <li><a href="#">Single Review</a></li>
                </ul>
            </li>
        </ul>
    </nav> <!-- End Main-Navigation -->