<div class="span6 post #nomargin#">
    <figure>
        <img src="/dist/tim.php?src=/dist/#images#&w=375&h=178" alt="#title#" />
        <div class="cat-name">
            <span class="base">#categoria#</span>
            <span class="arrow"></span>
        </div>
    </figure>
    <div class="text">
        <h2><a href="#url#" title="#title#"">#title#</a></h2>
        <p>#description#</p>
        <div class="meta">#mes# . #dia#, #ano#&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#url#">#empresa_views# Visualizações</a></div>
    </div>
</div>