<div class="col-md-3&#x20;col-sm-6&#x20;col-xs-12&#x20;col-box-list">
<div class="pricing">
<div class="title">
<h1>{{title}}</h1>
</div>
<div class="x_content">
<div>
<div class="pricing_features">
    <ul class="list-unstyled&#x20;text-left">
        <li><strong>{{images}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{cnpj}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{email}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{phone}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{cidade}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{cep}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{bairro}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{endereco}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{description}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{state}}</strong></li>
         <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{created}}</strong></li>
        <li><i class="fa&#x20;fa-check&#x20;&#x20;text-success"></i>
            <strong>{{modified}}</strong></li></ul>
</div></div>
<div class="pricing_footer">
{{buttons}}
</div>
</div>
</div></div>