<div class="form-comment">
        <h4>Deixe um comentario</h4>
           <label class="font-required"><?php echo $this->translate('{{description}}');?></label>
            #description#
            <label class="font-required"><?php echo $this->translate('{{nota}}');?></label>
            #nota#
             <input type="submit" name="submit" value="Submit Comment" />
           #id#
        #codigo#
        #empresa#
        #asset_id#
        #modified#
        #created#
        #security#
        #parent#
        #parent_id#
        #tipo##title#
        #access#
        #state#
        #created_by#
    <div class="margin-bottom20"></div>
    <div id="output"></div>
    </div> <!-- End Form-Comment -->
