<div class="margin-top40"></div>
<div class="span6 offset3">
       <div class="form-comment">
           <h4>Informe Seus Dados De Acesso!</h4>
           <div class="margin-bottom20"></div>
           <?php echo $this->translate('{{email}}');?>
           #email#
           <div class="margin-bottom20"></div>
           <?php echo $this->translate('{{password}}');?>
           #password#
           <div class="margin-bottom20"></div>
           <input type="submit" name="submit" value="Logar" />
           #security#
           <div class="margin-bottom20"></div>
           <div id="output"></div>
       </div> <!-- End Form-Comment -->
    <div class="margin-bottom30"></div>
   </div>


