<div class="rate-details">
    <div class="header">
        <h4>Review Overview</h4>
    </div>

    <div class="base-rate"> <!-- One -->
        <div class="rate-text">
            <span class="left">Expensive</span>
            <span class="right">92%</span>
        </div>
        <div style="width:92%;" class="rate-val"></div>
    </div>

    <div class="base-rate"> <!-- Two -->
        <div class="rate-text">
            <span class="left">Beautiful</span>
            <span class="right">86%</span>
        </div>
        <div style="width:86%;" class="rate-val"></div>
    </div>

    <div class="base-rate"> <!-- Three -->
        <div class="rate-text">
            <span class="left">Design</span>
            <span class="right">98%</span>
        </div>
        <div style="width:98%;" class="rate-val"></div>
    </div>

    <div class="base-rate"> <!-- Four -->
        <div class="rate-text">
            <span class="left">Inspirational</span>
            <span class="right">87%</span>
        </div>
        <div style="width:87%;" class="rate-val"></div>
    </div>

    <div class="base-rate"> <!-- Five -->
        <div class="rate-text">
            <span class="left">Style</span>
            <span class="right">96%</span>
        </div>
        <div style="width:96%;" class="rate-val"></div>
    </div>

    <div class="rate-overall"> <!-- Overall -->
        <div class="rating">
            <h2>91<sup>%</sup></h2>
            <p>Excellent</p>
        </div>
        <div class="desc">
            <p>Enter a rating summary here. You can do a short summary, or even a pros and cons list.</p>
        </div>
    </div>

</div>