<div class="row">
    <div class="span10 offset1">
        <div class="row">
           <div class="span12">
               #attachment#
                <p class="help-block">Max. 32MB</p>
            </div>
        </div>
        <div class="row">
             <div class="span8">
                <div class="" for="">
                    <?php echo $this->translate('{{title}}');?></div><div class="">
                    #title#</div>
            </div>
             <div class="span4">
                <div class="" for="">
                    <?php echo $this->translate('{{cnpj}}');?></div><div class="">
                    #cnpj#</div>
            </div>
        </div>
        <div class="row">
            <div class="span4">
                <div class="" for="">
                    <?php echo $this->translate('{{phone}}');?></div><div class="">
                    #phone#</div>
            </div>
            <div class="span8">
                <div class="" for="">
                    <?php echo $this->translate('{{email}}');?></div><div class="">
                    #email#</div>
            </div>
        </div>

        <div class="row">
            <div class="span4">
                <div class="" for="">
                    <?php echo $this->translate('{{cidade}}');?></div><div class="">
                    #cidade#</div>
            </div>

            <div class="span5">
                <div class="" for="">
                    <?php echo $this->translate('{{endereco}}');?></div><div class="">
                    #endereco#</div>
            </div>
            <div class="span3">
                <div class="" for="">
                    <?php echo $this->translate('{{bairro}}');?></div><div class="">
                    #bairro#</div>
            </div>

        </div>
        <div class="row">
            <div class="span2">
                <div class="" for="">
                    <?php echo $this->translate('{{cep}}');?></div><div class="">
                    #cep#</div>
            </div>
            <div class="span4">
                <div class="" for="">
                    <?php echo $this->translate('{{state}}');?></div><div class="">
                    #state#</div>
            </div>

            <div class="span3">
                <div class="" for="">
                    <?php echo $this->translate('{{created}}');?></div><div class="">
                    #created#<span class=""></span></div>
            </div>
            <div class="span3">
                <div class="" for="">
                    <?php echo $this->translate('{{password}}');?></div><div class="">
                    #password#<span class=""></span></div>
            </div>

        </div>
        <div class="row">
            <div class="span12">
                <div class="" for="">
                    <?php echo $this->translate('{{description}}');?></div><div class="">
                    #description#</div>
            </div>
            #id##codigo##empresa##asset_id##modified##security##url##images#
            #access#
            #url#
            #role_id#
            #usr_registration_token#
        </div>
        <div class="margin-bottom20"></div>
        <input type="submit" value="ATUALIZAR MEUS DADOS" name="save">
    </div>
</div> <!-- End Form-Comment -->
