<div class="margin-top40"></div>
<div class="form-comment">
    <fildset>
        <legend>FORMULARIO MINHA EMPRESA</legend>
        <div class="row">
            <div class="span3">
                <figure>#imagePreview# </figure>
            </div>
            <div class="span8">
                <input name="attachment" type="file" id="attachment" style="margin-top: 76px;" />
                <p class="help-block">Max. 32MB</p>
            </div>
        </div>
        <div class="row">
            <div class="span4">
                <div class="" for="">
                    <?php echo $this->translate('{{catid}}');?></div><div class="">
                    #catid#</div>
            </div>

            <div class="span8">
                <div class="" for="">
                    <?php echo $this->translate('{{title}}');?></div><div class="">
                    #title#</div>
            </div>
        </div>
        <div class="row">
            <div class="span4">
                <div class="" for="">
                    <?php echo $this->translate('{{phone}}');?></div><div class="">
                    #phone#</div>
            </div>
             <div class="span8">
                <div class="" for="">
                    <?php echo $this->translate('{{email}}');?></div><div class="">
                    #email#</div>
            </div>
        </div>
         <div class="row">
            <div class="span6">
                <div class="" for="">
                    <?php echo $this->translate('{{site}}');?></div><div class="">
                    #site#</div>
            </div>

            <div class="span6">
                <div class="" for="">
                    <?php echo $this->translate('{{facebook}}');?></div><div class="">
                    #facebook#</div>
            </div>
        </div>
        
        <div class="row">
            <div class="span3">
                <div class="" for="">
                    <?php echo $this->translate('{{classifcados_views}}');?></div><div class="">
                    #classifcados_views#</div>
            </div>
            <div class="span3">
                <div class="" for="">
                    <?php echo $this->translate('{{state}}');?></div><div class="">
                    #state#</div>
            </div>
           <div class="span3">
                <div class="" for="">
                    <?php echo $this->translate('{{created}}');?></div><div class="">
                    #created#<span class=""></span></div>
            </div>
        </div>
       <div class="row">
            <div class="span12">
                <div class="" for="">
                    <?php echo $this->translate('{{description}}');?></div><div class="">
                    #description#</div>
            </div>
            #id##codigo##empresa##asset_id##modified##security##url##images#
            #created_by##access#
        </div>
        <div class="margin-bottom20"></div>
        <input type="submit" value="ATUALIZAR DADOS DA EMPRESA" name="save">
    </fildset>
    <script src="/js/tinymce/tinymce.min.js" type="text/javascript"></script>
    <script src="/js/tinymce.init.js" type="text/javascript"></script>
    <script>
        intTinymce("#description");
    </script>
</div> <!-- End Form-Comment -->
<div class="margin-bottom30"></div>
