<div class="form-comment">
        <h4>Deixe um comentario</h4>
            <?php echo $this->translate('{{title}}');?>
            #title#
    <div class="margin-bottom20"></div>
            <?php echo $this->translate('{{email}}');?>
            #email#
    <div class="margin-bottom20"></div>
           <?php echo $this->translate('{{phone}}');?>
            #phone#
    <div class="margin-bottom20"></div>
            <?php echo $this->translate('{{password}}');?>
            #password#
    <div class="margin-bottom20"></div>
            <?php echo $this->translate('{{usr_password_confirm}}');?>
            #usr_password_confirm#
    <div class="margin-bottom20"></div>
           <?php echo $this->translate('{{captcha}}');?>
            #captcha#
    <div class="margin-bottom20"></div>
           <?php echo $this->translate('{{description}}');?>
            #description#
            <div class="margin-bottom20"></div>
             <input type="submit" name="submit" value="Cadastrar" />
           #id#
        #codigo#
        #empresa#
        #asset_id#
        #modified#
        #created#
        #cnpj#
        #security#
         #access#
        #state#
        #cidade#
        #cep#
        #endereco#
        #bairro#
        #role_id#
        #images#
        #usr_registration_token#

    <div class="margin-bottom20"></div>
    <div id="output"></div>
    </div> <!-- End Form-Comment -->
