
    <!-- One -->
    <div class="item span3 #nomargin#">
        <a href="#url#">
            <figure class="figure-hover">
                <img src="/dist/tim.php?src=/dist/#images#&w=120&h=120" alt="#title#" />
                <div class="figure-hover-masked">
                    <p class="icon-plus"></p>
                </div>
            </figure>
        </a>
        <p>#title#</p>
    </div>
