<div class="sponsors">

        <div class="header">
            <h4>Sponsors</h4>
        </div>

        <div class="content">
            <img src="/Portal_city556622/stretched/images/ads/180x180.png" alt="Sponsor 1" />
            <img src="/Portal_city556622/stretched/images/ads/180x180.png" alt="Sponsor 2" />
            <img src="/Portal_city556622/stretched/images/ads/180x180.png" alt="Sponsor 3" />
            <img src="/Portal_city556622/stretched/images/ads/180x180.png" alt="Sponsor 4" />
            <img src="/Portal_city556622/stretched/images/ads/180x180.png" alt="Sponsor 1" />
            <img src="/Portal_city556622/stretched/images/ads/180x180.png" alt="Sponsor 2" />
            <img src="/Portal_city556622/stretched/images/ads/180x180.png" alt="Sponsor 3" />
            <img src="/Portal_city556622/stretched/images/ads/180x180.png" alt="Sponsor 4" />

        </div>

    </div>